import { Supplier, Contract, GlobalAlert, LiveEvent, Shipment, CrisisRoom } from "@/types";

const NOW = "Updated: 3 days ago";

export const suppliersGoverned: Supplier[] = [
  {
    id: "pg",
    name: "Meridian Chemicals",
    ticker: "MCH",
    tier: 1,
    category: "Raw Materials",
    categoryConfidence: "High",
    region: "NA",
    duns: "11-422-8801",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: NOW, confidence: "HIGH" },
    ratios: { debtToEquity: 0.66, netProfitMargin: 0.191, currentRatio: 0.70 },
    cash: { exposureAtRisk: 4.6, cashRetained: 2.1, safetyStockDays: 14 },
    observation: { day: 47, total: 90, progressPct: 52 },
    approvals: { procurement: true, finance: true },
    checklist: { contractExecuted: true, opsStable: true, financeRecovery: false },
    spend: 14.6,
    exposure: 4.6,
    risk: 58,
    onTime: 91,
    qualityPPM: 180,
    creditRisk: {
      friskScore: 4,
      insolvencyProbability: 0.07,
      creditRating: "BB",
      paymentBehavior: "Moderate",
      bankruptcyRisk12m: "Moderate",
      lastUpdated: "3 days ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 61,
      grade: "C",
      environmental: 58,
      social: 64,
      governance: 62,
      eudrCompliant: "In Progress",
      csdddStatus: "In Progress",
      lksgStatus: "Compliant",
      csrdStatus: "In Progress",
      laborRisk: "Low",
      environmentalRisk: "Medium",
      carbonFootprint: "18.4kt CO₂e",
      lastAudit: "Aug 2025",
    },
    resiliency: {
      overall: 5.8,
      transparency: 6.2,
      network: 5.1,
      continuity: 5.9,
      performance: 6.4,
      maturity: 5.4,
      lastUpdated: "Q3 2025",
    },
    alerts: [{ id: "al-pg-1", type: "results", text: "FY2025 results published — liquidity signal", date: "2025-07-29" }],
    timeline: [
      { date: "Sep 02", text: "Liquidity signal detected (current ratio < 1.0)" },
      { date: "Sep 04", text: "Renegotiation initiated by procurement" },
      { date: "Sep 10", text: "Contract terms executed with 12-month review clause" },
      { date: "Sep 11", text: "Observation window started (90-day)" },
      { date: "Oct 28", text: "Finance validation pending — checkpoint due" },
    ],
  },
  {
    id: "sup-b",
    name: "Apex Components",
    tier: 2,
    category: "Components",
    categoryConfidence: "Medium",
    region: "EU",
    duns: "22-188-4492",
    riskState: "MITIGATION IN PROGRESS",
    data: { updatedLabel: "Updated: 7 days ago", confidence: "MEDIUM" },
    risk: 41,
    spend: 7.9,
    exposure: 7.1,
    onTime: 95,
    qualityPPM: 140,
    creditRisk: {
      friskScore: 7,
      insolvencyProbability: 0.02,
      creditRating: "BBB",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "7 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 78,
      grade: "B",
      environmental: 80,
      social: 76,
      governance: 79,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "In Progress",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "9.1kt CO₂e",
      lastAudit: "Jun 2025",
    },
    resiliency: {
      overall: 7.4,
      transparency: 7.8,
      network: 7.0,
      continuity: 7.6,
      performance: 7.5,
      maturity: 7.1,
      lastUpdated: "Q3 2025",
    },
    alerts: [{ id: "al-b-1", type: "logistics", text: "Port congestion impacting lead time", date: "2025-09-18" }],
  },
  {
    id: "sup-a",
    name: "Borealis Plastics",
    tier: 1,
    category: "Raw Materials",
    categoryConfidence: "High",
    region: "APAC",
    duns: "33-917-2201",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: "Updated: 2 days ago", confidence: "HIGH" },
    risk: 78,
    spend: 12.4,
    exposure: 12.0,
    onTime: 89,
    qualityPPM: 220,
    creditRisk: {
      friskScore: 2,
      insolvencyProbability: 0.19,
      creditRating: "B-",
      paymentBehavior: "Poor",
      bankruptcyRisk12m: "High",
      lastUpdated: "2 days ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 44,
      grade: "D",
      environmental: 38,
      social: 49,
      governance: 46,
      eudrCompliant: "Not Started",
      csdddStatus: "Non-Compliant",
      lksgStatus: "In Progress",
      csrdStatus: "Not Started",
      laborRisk: "High",
      environmentalRisk: "High",
      carbonFootprint: "31.7kt CO₂e",
      lastAudit: "Mar 2024",
    },
    resiliency: {
      overall: 3.9,
      transparency: 3.2,
      network: 4.1,
      continuity: 3.8,
      performance: 4.4,
      maturity: 4.0,
      lastUpdated: "Q2 2025",
    },
    alerts: [{ id: "al-a-1", type: "risk", text: "Credit outlook downgraded by Moody's", date: "2025-09-12" }],
  },
];

export const suppliersDirectory: Supplier[] = [
  {
    id: "sup-001",
    name: "Halsted Manufacturing",
    tier: 1,
    region: "NA",
    duns: "44-211-9983",
    risk: 78,
    spend: 12.4,
    onTime: 89,
    qualityPPM: 220,
    exposure: 12.0,
    category: "Components",
    categoryConfidence: "Medium",
    riskState: "MITIGATION IN PROGRESS",
    data: { updatedLabel: "Updated: 5 days ago", confidence: "MEDIUM" },
    creditRisk: {
      friskScore: 3,
      insolvencyProbability: 0.14,
      creditRating: "B",
      paymentBehavior: "Moderate",
      bankruptcyRisk12m: "High",
      lastUpdated: "5 days ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 53,
      grade: "C",
      environmental: 50,
      social: 55,
      governance: 54,
      eudrCompliant: "In Progress",
      csdddStatus: "In Progress",
      lksgStatus: "In Progress",
      csrdStatus: "Not Started",
      laborRisk: "Medium",
      environmentalRisk: "Medium",
      carbonFootprint: "22.1kt CO₂e",
      lastAudit: "May 2025",
    },
    resiliency: {
      overall: 4.2,
      transparency: 4.8,
      network: 3.9,
      continuity: 4.1,
      performance: 4.6,
      maturity: 3.6,
      lastUpdated: "Q3 2025",
    },
    alerts: [
      { id: "al-1", type: "risk", text: "Credit outlook downgraded", date: "2025-09-12" },
      { id: "al-2", type: "contract", text: "MSA renewal due in 45 days", date: "2025-09-21" },
    ],
  },
  {
    id: "sup-002",
    name: "Osaka Precision",
    tier: 2,
    region: "EU",
    duns: "55-304-1122",
    risk: 41,
    spend: 7.9,
    onTime: 95,
    qualityPPM: 140,
    exposure: 7.1,
    category: "Raw Materials",
    categoryConfidence: "Medium",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: "Updated: 7 days ago", confidence: "MEDIUM" },
    creditRisk: {
      friskScore: 8,
      insolvencyProbability: 0.01,
      creditRating: "A-",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "7 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 82,
      grade: "A",
      environmental: 85,
      social: 80,
      governance: 83,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "Compliant",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "6.3kt CO₂e",
      lastAudit: "Sep 2025",
    },
    resiliency: {
      overall: 8.1,
      transparency: 8.4,
      network: 7.9,
      continuity: 8.3,
      performance: 8.2,
      maturity: 7.7,
      lastUpdated: "Q3 2025",
    },
    alerts: [{ id: "al-3", type: "logistics", text: "Port congestion impacting lead time", date: "2025-09-18" }],
  },
  {
    id: "sup-003",
    name: "Chimera Alloys",
    tier: 3,
    region: "APAC",
    duns: "66-511-7734",
    risk: 62,
    spend: 3.1,
    onTime: 78,
    qualityPPM: 380,
    exposure: 4.3,
    category: "Raw Materials",
    categoryConfidence: "Low",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: "Updated: 10 days ago", confidence: "LOW" },
    creditRisk: {
      friskScore: 5,
      insolvencyProbability: 0.06,
      creditRating: "BB-",
      paymentBehavior: "Moderate",
      bankruptcyRisk12m: "Moderate",
      lastUpdated: "10 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 37,
      grade: "D",
      environmental: 32,
      social: 41,
      governance: 38,
      eudrCompliant: "Not Started",
      csdddStatus: "Non-Compliant",
      lksgStatus: "Non-Compliant",
      csrdStatus: "Not Started",
      laborRisk: "High",
      environmentalRisk: "High",
      carbonFootprint: "48.2kt CO₂e",
      lastAudit: "Jan 2024",
    },
    resiliency: {
      overall: 3.4,
      transparency: 2.9,
      network: 3.5,
      continuity: 3.2,
      performance: 3.8,
      maturity: 3.6,
      lastUpdated: "Q2 2025",
    },
    alerts: [{ id: "al-4", type: "quality", text: "Defect spike — last 30 days", date: "2025-09-08" }],
  },
  {
    id: "sup-004",
    name: "Vantage Logistics EU",
    tier: 1,
    region: "EU",
    duns: "77-849-3301",
    risk: 22,
    spend: 9.1,
    onTime: 97,
    qualityPPM: 80,
    exposure: 5.2,
    category: "Logistics",
    categoryConfidence: "High",
    riskState: "STABLE",
    data: { updatedLabel: "Updated: 1 day ago", confidence: "HIGH" },
    creditRisk: {
      friskScore: 9,
      insolvencyProbability: 0.005,
      creditRating: "A+",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "1 day ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 88,
      grade: "A",
      environmental: 91,
      social: 86,
      governance: 88,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "Compliant",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "4.8kt CO₂e",
      lastAudit: "Sep 2025",
    },
    resiliency: {
      overall: 9.1,
      transparency: 9.4,
      network: 9.0,
      continuity: 9.2,
      performance: 9.1,
      maturity: 8.8,
      lastUpdated: "Q3 2025",
    },
    alerts: [],
  },
  {
    id: "sup-005",
    name: "Durban Steel Works",
    tier: 2,
    region: "APAC",
    duns: "88-663-2290",
    risk: 71,
    spend: 5.6,
    onTime: 82,
    qualityPPM: 310,
    exposure: 6.8,
    category: "Raw Materials",
    categoryConfidence: "Medium",
    riskState: "ESCALATED",
    data: { updatedLabel: "Updated: 12 days ago", confidence: "MEDIUM" },
    creditRisk: {
      friskScore: 2,
      insolvencyProbability: 0.22,
      creditRating: "CCC",
      paymentBehavior: "Poor",
      bankruptcyRisk12m: "Critical",
      lastUpdated: "12 days ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 29,
      grade: "F",
      environmental: 22,
      social: 34,
      governance: 31,
      eudrCompliant: "Not Started",
      csdddStatus: "Non-Compliant",
      lksgStatus: "Non-Compliant",
      csrdStatus: "Not Started",
      laborRisk: "High",
      environmentalRisk: "High",
      carbonFootprint: "61.4kt CO₂e",
      lastAudit: "Dec 2023",
    },
    resiliency: {
      overall: 2.8,
      transparency: 2.2,
      network: 2.9,
      continuity: 2.7,
      performance: 3.2,
      maturity: 3.0,
      lastUpdated: "Q2 2025",
    },
    alerts: [{ id: "al-5", type: "quality", text: "Third consecutive quality non-conformance", date: "2025-09-01" }],
  },
];

export const CONTRACTS: Contract[] = [
  { id: "co-01", supplierId: "sup-001", supplierName: "Halsted Manufacturing", title: "MSA-2024", type: "Master Services", expires: "2025-11-10", value: "$12.4M", status: "Active", autoRenew: false },
  { id: "co-02", supplierId: "sup-002", supplierName: "Osaka Precision", title: "QPA-Resin", type: "Quality & Price", expires: "2025-10-15", value: "$7.9M", status: "Pending Renewal", autoRenew: true },
  { id: "co-03", supplierId: "sup-003", supplierName: "Chimera Alloys", title: "LTA-Titanium", type: "Long-term Agreement", expires: "2026-01-30", value: "$3.1M", status: "Active", autoRenew: false },
  { id: "co-04", supplierId: "pg", supplierName: "Meridian Chemicals", title: "SLA-Chem-2023", type: "Supply & Service", expires: "2026-04-01", value: "$14.6M", status: "Under Renegotiation", autoRenew: false },
  { id: "co-05", supplierId: "sup-004", supplierName: "Vantage Logistics EU", title: "LOG-FRAME-24", type: "Framework", expires: "2026-06-30", value: "$9.1M", status: "Active", autoRenew: true },
];

export const GLOBAL_ALERTS: GlobalAlert[] = [
  { id: "ga-01", supplierId: "sup-003", text: "Shipment SHP-8841 — customs hold, 6-day delay", type: "logistics", date: "2h ago" },
  { id: "ga-02", supplierId: "sup-001", text: "Risk score elevated to 78 — credit downgrade", type: "risk", date: "41m ago" },
  { id: "ga-03", supplierId: "sup-002", text: "Contract QPA-Resin renewal window open (30 days)", type: "contract", date: "1d ago" },
  { id: "ga-04", supplierId: "pg", text: "Meridian Chemicals observation day 47/90 — checkpoint due", type: "observation", date: "3d ago" },
];

// ── Live Disruption Events (Everstream equivalent) ────────────────────────────
export const LIVE_EVENTS: LiveEvent[] = [
  {
    id: "ev-001",
    category: "natural_disaster",
    severity: "critical",
    title: "Typhoon Krathon — South China Sea",
    detail: "Category 4 typhoon tracking toward Taiwan Strait. Major disruption expected to shipping lanes and manufacturing sites in southern Taiwan and Guangdong province.",
    region: "APAC",
    country: "Taiwan / China",
    affectedSupplierIds: ["sup-a", "sup-003"],
    estimatedImpact: "$14.2M exposure at risk",
    leadTimeExtension: "12–18 days",
    date: "2h ago",
    source: "NOAA / Everstream signal",
    status: "Active",
    predictedEnd: "Oct 14, 2025",
  },
  {
    id: "ev-002",
    category: "geopolitical",
    severity: "high",
    title: "Red Sea shipping disruptions — Houthi activity",
    detail: "Continued Houthi attacks on commercial vessels in the Red Sea and Gulf of Aden. Major carriers rerouting via Cape of Good Hope, adding 14+ transit days.",
    region: "EMEA",
    country: "Yemen / Red Sea",
    affectedSupplierIds: ["sup-b", "sup-002"],
    estimatedImpact: "$3.8M freight cost increase",
    leadTimeExtension: "14–21 days",
    date: "6h ago",
    source: "Maritime Intelligence / Lloyd's",
    status: "Active",
  },
  {
    id: "ev-003",
    category: "labor",
    severity: "high",
    title: "Port of Durban — Dockworker strike",
    detail: "TRANSNET dockworkers initiated indefinite strike over wage dispute. All container operations suspended at South Africa's largest port. Affecting APAC-EU shipments.",
    region: "APAC",
    country: "South Africa",
    affectedSupplierIds: ["sup-005"],
    estimatedImpact: "$6.8M at risk",
    leadTimeExtension: "7–14 days",
    date: "1d ago",
    source: "ILO / Reuters",
    status: "Active",
  },
  {
    id: "ev-004",
    category: "financial",
    severity: "high",
    title: "Borealis Plastics — Moody's credit downgrade",
    detail: "Moody's downgraded Borealis Plastics from Ba2 to B1, citing deteriorating liquidity position and elevated leverage. FRISK score fell from 3 to 2.",
    region: "APAC",
    country: "Singapore",
    affectedSupplierIds: ["sup-a"],
    estimatedImpact: "$12.0M exposure",
    date: "2d ago",
    source: "Moody's / CreditRiskMonitor",
    status: "Active",
  },
  {
    id: "ev-005",
    category: "logistics",
    severity: "medium",
    title: "Rotterdam Port — Customs IT system outage",
    detail: "Dutch customs authority Douane experiencing system outage impacting automated clearance. Manual processing causing 3–5 day delays at EU's largest container port.",
    region: "EU",
    country: "Netherlands",
    affectedSupplierIds: ["sup-b", "sup-002", "sup-004"],
    estimatedImpact: "$2.1M delay costs",
    leadTimeExtension: "3–5 days",
    date: "3d ago",
    source: "Port of Rotterdam / Douane",
    status: "Monitoring",
  },
  {
    id: "ev-006",
    category: "regulatory",
    severity: "medium",
    title: "EU CSDDD enforcement — Q4 2025 deadline",
    detail: "European Corporate Sustainability Due Diligence Directive enters enforcement phase. Companies with >500 employees must demonstrate supplier compliance across Tier 1 and Tier 2.",
    region: "EU",
    country: "EU-wide",
    affectedSupplierIds: ["sup-001", "sup-003", "sup-005"],
    estimatedImpact: "Regulatory penalty risk",
    date: "5d ago",
    source: "European Commission",
    status: "Monitoring",
  },
  {
    id: "ev-007",
    category: "cyber",
    severity: "medium",
    title: "Halsted Manufacturing — Ransomware incident",
    detail: "Halsted Manufacturing confirmed a ransomware incident affecting its MES and ERP systems at the Peoria, IL facility. Production partially suspended pending system restoration.",
    region: "NA",
    country: "United States",
    affectedSupplierIds: ["sup-001"],
    estimatedImpact: "$4.3M revenue at risk",
    leadTimeExtension: "5–10 days",
    date: "4d ago",
    source: "Halsted IR Disclosure / CISA",
    status: "Active",
  },
  {
    id: "ev-008",
    category: "quality",
    severity: "low",
    title: "Chimera Alloys — Titanium alloy batch non-conformance",
    detail: "Third consecutive non-conformance event on titanium alloy batch TA-4412. Hardness deviation of 8% outside spec. Full batch quarantine initiated, root cause under investigation.",
    region: "APAC",
    country: "South Korea",
    affectedSupplierIds: ["sup-003"],
    estimatedImpact: "$0.8M quarantine cost",
    date: "6d ago",
    source: "Internal QMS",
    status: "Active",
  },
];

// ── Shipments / Logistics (Everstream equivalent) ─────────────────────────────
export const SHIPMENTS: Shipment[] = [
  { id: "SHP-8841", supplierId: "sup-003", origin: "Incheon, KR", destination: "Rotterdam, NL", carrier: "Maersk", eta: "Oct 22, 2025", delayDays: 6, delayRisk: "High", status: "Customs Hold", value: "$0.9M" },
  { id: "SHP-9014", supplierId: "sup-a", origin: "Singapore, SG", destination: "Long Beach, CA", carrier: "COSCO", eta: "Oct 18, 2025", delayDays: 14, delayRisk: "High", status: "Delayed", value: "$3.2M" },
  { id: "SHP-9102", supplierId: "sup-b", origin: "Hamburg, DE", destination: "New York, NY", carrier: "Hapag-Lloyd", eta: "Oct 15, 2025", delayDays: 3, delayRisk: "Medium", status: "At Risk", value: "$1.8M" },
  { id: "SHP-9230", supplierId: "sup-004", origin: "Antwerp, BE", destination: "Felixstowe, UK", carrier: "MSC", eta: "Oct 12, 2025", delayRisk: "Low", status: "On Track", value: "$2.1M" },
  { id: "SHP-9318", supplierId: "sup-002", origin: "Yokohama, JP", destination: "Hamburg, DE", carrier: "NYK", eta: "Oct 25, 2025", delayDays: 18, delayRisk: "High", status: "Delayed", value: "$1.4M" },
  { id: "SHP-9401", supplierId: "sup-001", origin: "Chicago, IL", destination: "Memphis, TN", carrier: "FedEx Freight", eta: "Oct 11, 2025", delayRisk: "Low", status: "On Track", value: "$0.6M" },
  { id: "SHP-9488", supplierId: "pg", origin: "Houston, TX", destination: "Detroit, MI", carrier: "XPO Logistics", eta: "Oct 13, 2025", delayRisk: "Low", status: "On Track", value: "$2.4M" },
];

// ── Crisis Rooms (Resilinc WarRoom equivalent) ────────────────────────────────
export const CRISIS_ROOMS: CrisisRoom[] = [
  {
    id: "cr-001",
    title: "Typhoon Krathon — APAC Supply Impact",
    triggeredBy: "ev-001",
    severity: "critical",
    openedDate: "Oct 09, 2025",
    owner: "Sarah Renwick",
    affectedSupplierIds: ["sup-a", "sup-003"],
    affectedParts: ["Resin RP-44", "Resin RP-61", "Ti Alloy TA-4412", "Ti Alloy TA-4800"],
    estimatedExposure: "$16.3M",
    status: "Open",
    actions: [
      { id: "a1", text: "Activate safety stock for Resin RP-44 (14-day buffer)", owner: "J. Park — Ops", due: "Oct 10", done: true },
      { id: "a2", text: "Qualify Nexus Polymers as emergency alternate for Borealis Plastics", owner: "M. Chen — Procurement", due: "Oct 14", done: false },
      { id: "a3", text: "Reroute Chimera Alloys shipment SHP-8841 via air freight", owner: "D. Okafor — Logistics", due: "Oct 11", done: false },
      { id: "a4", text: "Notify affected production lines — Tier 1 shortage signal", owner: "T. Vasquez — Planning", due: "Oct 10", done: true },
    ],
  },
  {
    id: "cr-002",
    title: "Halsted Manufacturing — Cyber Incident",
    triggeredBy: "ev-007",
    severity: "high",
    openedDate: "Oct 06, 2025",
    owner: "A. Bhattacharya",
    affectedSupplierIds: ["sup-001"],
    affectedParts: ["Connector Asm C-220", "PCB Sub-Assembly PA-08", "Housing Unit HU-14"],
    estimatedExposure: "$4.3M",
    status: "Open",
    actions: [
      { id: "b1", text: "Confirm Halsted production resumption ETA", owner: "M. Chen — Procurement", due: "Oct 08", done: true },
      { id: "b2", text: "Increase safety stock for C-220 to 30 days", owner: "J. Park — Ops", due: "Oct 09", done: true },
      { id: "b3", text: "Evaluate secondary source — Apex Components for C-220", owner: "M. Chen — Procurement", due: "Oct 15", done: false },
      { id: "b4", text: "Trigger MSA force majeure clause review with Legal", owner: "Legal", due: "Oct 12", done: false },
    ],
  },
  {
    id: "cr-003",
    title: "Red Sea Rerouting — EU-bound Shipments",
    triggeredBy: "ev-002",
    severity: "high",
    openedDate: "Oct 04, 2025",
    owner: "D. Okafor",
    affectedSupplierIds: ["sup-b", "sup-002"],
    affectedParts: ["Component CP-118", "Precision Part PP-44"],
    estimatedExposure: "$3.8M",
    status: "Contained",
    actions: [
      { id: "c1", text: "Reroute all EU-bound shipments via Cape of Good Hope", owner: "D. Okafor — Logistics", due: "Oct 05", done: true },
      { id: "c2", text: "Negotiate expedited freight surcharge with Hapag-Lloyd", owner: "D. Okafor — Logistics", due: "Oct 07", done: true },
      { id: "c3", text: "Adjust production schedule — 14-day buffer on CP-118 line", owner: "T. Vasquez — Planning", due: "Oct 08", done: true },
    ],
  },
];

export const suppliersAll: Supplier[] = [
  ...suppliersGoverned,
  ...suppliersDirectory.filter((s) => !suppliersGoverned.find((g) => g.id === s.id)),
];
