import { Supplier, Contract, GlobalAlert, LiveEvent, Shipment, CrisisRoom, RecoveryProfile, Certification, ProductLine, CommodityPrice, Assessment, IndustryBenchmark, DataFeed } from "@/types";
import { computeRisk } from "@/lib/analytics";

const NOW = "Updated: 2 days ago";

// ── Governed Suppliers (risk-managed, with full profiles) ─────────────────────
export const suppliersGoverned: Supplier[] = [
  {
    id: "sit",
    name: "SIT Group",
    ticker: undefined,
    website: "https://www.sit.it",
    countryCode: "IT",
    riskHistory: [44, 46, 47, 49, 51, 53, 55, 57, 59, 61, 62, 64],
    tier: 1,
    category: "Components",
    categoryConfidence: "High",
    region: "EU",
    duns: "43-229-8871",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: NOW, confidence: "HIGH" },
    ratios: { debtToEquity: 1.82, netProfitMargin: 0.048, currentRatio: 0.79 },
    financialHealth: {
      score: 28,
      dioTrend: [52, 58, 67, 76],
      dsoTrend: [34, 39, 46, 52],
      dpoCurrent: 48,
      cccTrend: [38, 49, 65, 80],
      inventoryGrowthYoY: 0.28,
      revenueGrowthYoY: -0.11,
      netDebtEbitda: [2.1, 2.4, 2.6, 2.9, 3.2, 3.6, 4.2, 4.8],
      interestCoverage: 1.8,
      capexToDepreciation: [0.92, 0.78, 0.64, 0.58],
      flags: [
        { type: "inventory", severity: "critical", text: "Inventory +28% YoY while revenue -11% — possible demand destruction" },
        { type: "dso", severity: "warn", text: "DSO expanded from 34 → 52 days — customers stretching payments" },
        { type: "leverage", severity: "warn", text: "Net Debt/EBITDA reached 4.8× — approaching critical 5× threshold" },
        { type: "capex", severity: "info", text: "CapEx/D&A at 0.58 — underinvesting relative to asset base" },
      ],
    },
    cash: { exposureAtRisk: 7.2, cashRetained: 2.8, safetyStockDays: 18 },
    observation: { day: 34, total: 90, progressPct: 38 },
    approvals: { procurement: true, finance: false },
    checklist: { contractExecuted: true, opsStable: false, financeRecovery: false },
    spend: 18.4,
    exposure: 7.2,
    risk: 64,
    onTime: 88,
    qualityPPM: 195,
    creditRisk: {
      friskScore: 3,
      insolvencyProbability: 0.11,
      creditRating: "BB-",
      paymentBehavior: "Moderate",
      bankruptcyRisk12m: "Moderate",
      lastUpdated: "2 days ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 67,
      grade: "C",
      environmental: 64,
      social: 69,
      governance: 68,
      eudrCompliant: "In Progress",
      csdddStatus: "In Progress",
      lksgStatus: "Compliant",
      csrdStatus: "In Progress",
      laborRisk: "Low",
      environmentalRisk: "Medium",
      carbonFootprint: "14.2kt CO₂e",
      lastAudit: "Jul 2025",
    },
    resiliency: {
      overall: 5.4,
      transparency: 5.8,
      network: 4.9,
      continuity: 5.2,
      performance: 5.7,
      maturity: 5.4,
      lastUpdated: "Q3 2025",
    },
    alerts: [
      { id: "al-sit-1", type: "risk", text: "FRISK score declined to 3 — liquidity warning", date: "2025-10-01" },
      { id: "al-sit-2", type: "contract", text: "Gas Controls MSA renewal due in 60 days", date: "2025-09-28" },
    ],
    timeline: [
      { date: "Sep 08", text: "Liquidity warning flagged — current ratio dropped below 0.8" },
      { date: "Sep 12", text: "Procurement initiated renegotiation review" },
      { date: "Sep 18", text: "Revised payment terms executed — net-60 extended to net-90" },
      { date: "Sep 20", text: "Observation window opened (90-day)" },
      { date: "Oct 15", text: "Ops stability checkpoint — production continuity maintained" },
      { date: "Nov 01", text: "Finance recovery milestone pending — balance sheet review due" },
    ],
  },
  {
    id: "ebm",
    name: "Ebm-papst",
    ticker: undefined,
    website: "https://www.ebmpapst.com",
    countryCode: "DE",
    riskHistory: [28, 29, 30, 32, 34, 35, 37, 39, 40, 40, 41, 41],
    tier: 1,
    category: "Components",
    categoryConfidence: "High",
    region: "EU",
    duns: "53-114-4421",
    riskState: "MITIGATION IN PROGRESS",
    data: { updatedLabel: "Updated: 5 days ago", confidence: "MEDIUM" },
    ratios: { debtToEquity: 0.58, netProfitMargin: 0.092, currentRatio: 1.38 },
    financialHealth: {
      score: 74,
      dioTrend: [38, 39, 38, 40],
      dsoTrend: [36, 37, 38, 38],
      dpoCurrent: 42,
      cccTrend: [32, 34, 34, 36],
      inventoryGrowthYoY: 0.03,
      revenueGrowthYoY: 0.06,
      netDebtEbitda: [1.2, 1.1, 1.0, 0.9, 0.9, 1.0, 1.0, 1.0],
      interestCoverage: 8.4,
      capexToDepreciation: [1.38, 1.41, 1.45, 1.44],
      flags: [
        { type: "revenue", severity: "info", text: "Revenue +6% YoY with stable inventory — healthy demand alignment" },
        { type: "capex", severity: "info", text: "CapEx/D&A at 1.44 — investing ahead of depreciation, supporting growth" },
      ],
    },
    spend: 11.7,
    exposure: 3.9,
    risk: 41,
    onTime: 93,
    qualityPPM: 145,
    creditRisk: {
      friskScore: 7,
      insolvencyProbability: 0.02,
      creditRating: "BBB+",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "5 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 81,
      grade: "B",
      environmental: 84,
      social: 79,
      governance: 80,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "In Progress",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "8.6kt CO₂e",
      lastAudit: "Aug 2025",
    },
    resiliency: {
      overall: 7.1,
      transparency: 7.4,
      network: 6.8,
      continuity: 7.3,
      performance: 7.2,
      maturity: 6.8,
      lastUpdated: "Q3 2025",
    },
    alerts: [{ id: "al-ebm-1", type: "logistics", text: "Fan motor lead times extended to 14 weeks due to magnet shortage", date: "2025-09-22" }],
  },
  {
    id: "aal",
    name: "Aalberts Industries",
    ticker: "AALB.AS",
    website: "https://www.aalberts.com",
    countryCode: "NL",
    riskHistory: [32, 35, 38, 42, 46, 50, 55, 61, 67, 71, 74, 76],
    tier: 2,
    category: "Components",
    categoryConfidence: "High",
    region: "EU",
    duns: "32-778-9903",
    riskState: "ESCALATED",
    data: { updatedLabel: "Updated: 1 day ago", confidence: "HIGH" },
    ratios: { debtToEquity: 2.14, netProfitMargin: 0.031, currentRatio: 0.71 },
    financialHealth: {
      score: 18,
      dioTrend: [61, 72, 88, 102],
      dsoTrend: [41, 44, 49, 54],
      dpoCurrent: 72,
      cccTrend: [30, 44, 65, 84],
      inventoryGrowthYoY: 0.41,
      revenueGrowthYoY: -0.08,
      netDebtEbitda: [2.8, 3.1, 3.6, 4.0, 4.4, 4.8, 5.1, 5.2],
      interestCoverage: 1.2,
      capexToDepreciation: [1.12, 0.98, 0.81, 0.72],
      flags: [
        { type: "inventory", severity: "critical", text: "Inventory +41% YoY while revenue -8% — significant overstock and demand risk" },
        { type: "leverage", severity: "critical", text: "Net Debt/EBITDA at 5.2× — exceeds typical 4× covenant threshold" },
        { type: "dpo", severity: "warn", text: "DPO at 72 days — stretching supplier payments signals acute cash strain" },
        { type: "margin", severity: "warn", text: "Net margin compressed to 3.1% — EBITDA missed guidance by 22%" },
        { type: "dso", severity: "warn", text: "DSO expanded 41 → 54 days — receivables quality deteriorating" },
      ],
    },
    spend: 8.3,
    exposure: 9.4,
    risk: 76,
    onTime: 81,
    qualityPPM: 290,
    creditRisk: {
      friskScore: 2,
      insolvencyProbability: 0.18,
      creditRating: "B",
      paymentBehavior: "Poor",
      bankruptcyRisk12m: "High",
      lastUpdated: "1 day ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 52,
      grade: "C",
      environmental: 48,
      social: 55,
      governance: 54,
      eudrCompliant: "In Progress",
      csdddStatus: "In Progress",
      lksgStatus: "In Progress",
      csrdStatus: "Not Started",
      laborRisk: "Medium",
      environmentalRisk: "Medium",
      carbonFootprint: "19.8kt CO₂e",
      lastAudit: "Apr 2025",
    },
    resiliency: {
      overall: 3.7,
      transparency: 3.2,
      network: 3.8,
      continuity: 3.5,
      performance: 4.1,
      maturity: 3.9,
      lastUpdated: "Q2 2025",
    },
    alerts: [
      { id: "al-aal-1", type: "risk", text: "Credit rating downgraded to B — high bankruptcy probability flagged", date: "2025-10-02" },
      { id: "al-aal-2", type: "results", text: "H1 2025 results missed guidance by 22% — EBITDA contraction", date: "2025-09-15" },
    ],
    timeline: [
      { date: "Aug 28", text: "H1 results disclosure — revenue and margin miss" },
      { date: "Sep 05", text: "Procurement escalated to VP Supply Chain" },
      { date: "Sep 15", text: "Credit rating downgraded by Moody's" },
      { date: "Oct 02", text: "Risk state escalated — secondary sourcing initiated" },
    ],
  },
];

// ── Directory Suppliers (broader supplier base) ───────────────────────────────
export const suppliersDirectory: Supplier[] = [
  {
    id: "gru",
    name: "Grundfos",
    ticker: undefined,
    website: "https://www.grundfos.com",
    countryCode: "DK",
    riskHistory: [26, 25, 27, 26, 28, 27, 26, 27, 28, 26, 27, 27],
    tier: 1,
    category: "Components",
    categoryConfidence: "High",
    region: "EU",
    duns: "18-334-7712",
    riskState: "STABLE",
    data: { updatedLabel: "Updated: 3 days ago", confidence: "HIGH" },
    ratios: { debtToEquity: 0.42, netProfitMargin: 0.118, currentRatio: 1.71 },
    financialHealth: {
      score: 88,
      dioTrend: [34, 33, 32, 32],
      dsoTrend: [38, 37, 38, 37],
      dpoCurrent: 45,
      cccTrend: [27, 25, 25, 24],
      inventoryGrowthYoY: 0.04,
      revenueGrowthYoY: 0.09,
      netDebtEbitda: [0.6, 0.6, 0.5, 0.5, 0.6, 0.5, 0.5, 0.4],
      interestCoverage: 18.2,
      capexToDepreciation: [1.52, 1.55, 1.58, 1.62],
      flags: [],
    },
    spend: 16.2,
    exposure: 4.1,
    risk: 27,
    onTime: 97,
    qualityPPM: 88,
    creditRisk: {
      friskScore: 9,
      insolvencyProbability: 0.004,
      creditRating: "A",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "3 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 89,
      grade: "A",
      environmental: 92,
      social: 87,
      governance: 88,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "Compliant",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "5.1kt CO₂e",
      lastAudit: "Sep 2025",
    },
    resiliency: {
      overall: 9.0,
      transparency: 9.2,
      network: 8.9,
      continuity: 9.1,
      performance: 9.0,
      maturity: 8.8,
      lastUpdated: "Q3 2025",
    },
    alerts: [],
  },
  {
    id: "dan",
    name: "Danfoss",
    ticker: undefined,
    website: "https://www.danfoss.com",
    countryCode: "DK",
    riskHistory: [28, 28, 29, 30, 30, 29, 30, 31, 31, 30, 31, 31],
    tier: 2,
    category: "Components",
    categoryConfidence: "High",
    region: "EU",
    duns: "29-445-6631",
    riskState: "STABLE",
    data: { updatedLabel: "Updated: 6 days ago", confidence: "HIGH" },
    ratios: { debtToEquity: 0.61, netProfitMargin: 0.108, currentRatio: 1.52 },
    financialHealth: {
      score: 79,
      dioTrend: [36, 35, 36, 35],
      dsoTrend: [40, 40, 39, 41],
      dpoCurrent: 43,
      cccTrend: [33, 32, 32, 33],
      inventoryGrowthYoY: 0.02,
      revenueGrowthYoY: 0.07,
      netDebtEbitda: [0.9, 0.8, 0.8, 0.9, 0.8, 0.8, 0.7, 0.7],
      interestCoverage: 14.6,
      capexToDepreciation: [1.28, 1.32, 1.35, 1.38],
      flags: [],
    },
    spend: 7.4,
    exposure: 2.3,
    risk: 31,
    onTime: 96,
    qualityPPM: 102,
    creditRisk: {
      friskScore: 8,
      insolvencyProbability: 0.01,
      creditRating: "A-",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "6 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 86,
      grade: "A",
      environmental: 89,
      social: 84,
      governance: 85,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "Compliant",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "6.4kt CO₂e",
      lastAudit: "Aug 2025",
    },
    resiliency: {
      overall: 8.4,
      transparency: 8.7,
      network: 8.2,
      continuity: 8.5,
      performance: 8.4,
      maturity: 8.2,
      lastUpdated: "Q3 2025",
    },
    alerts: [],
  },
  {
    id: "gfp",
    name: "Georg Fischer Piping Systems",
    ticker: "GF.SW",
    website: "https://www.georgfischer.com",
    countryCode: "CH",
    riskHistory: [38, 40, 41, 43, 44, 45, 46, 46, 47, 47, 48, 48],
    tier: 2,
    category: "Raw Materials",
    categoryConfidence: "Medium",
    region: "EU",
    duns: "47-891-2203",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: "Updated: 8 days ago", confidence: "MEDIUM" },
    ratios: { debtToEquity: 0.94, netProfitMargin: 0.071, currentRatio: 1.21 },
    financialHealth: {
      score: 52,
      dioTrend: [44, 47, 50, 53],
      dsoTrend: [42, 43, 44, 46],
      dpoCurrent: 44,
      cccTrend: [42, 46, 50, 55],
      inventoryGrowthYoY: 0.12,
      revenueGrowthYoY: 0.01,
      netDebtEbitda: [1.8, 2.0, 2.2, 2.4, 2.5, 2.6, 2.7, 2.8],
      interestCoverage: 4.1,
      capexToDepreciation: [1.21, 1.18, 1.12, 1.09],
      flags: [
        { type: "inventory", severity: "warn", text: "Inventory +12% on near-flat revenue — modest build-up worth monitoring" },
        { type: "ccc", severity: "warn", text: "Cash Conversion Cycle lengthening: 42 → 55 days over 4 quarters" },
        { type: "leverage", severity: "info", text: "Net Debt/EBITDA rising steadily: 1.8 → 2.8× — trajectory to watch" },
      ],
    },
    spend: 5.8,
    exposure: 3.6,
    risk: 48,
    onTime: 91,
    qualityPPM: 168,
    creditRisk: {
      friskScore: 6,
      insolvencyProbability: 0.04,
      creditRating: "BBB",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "8 days ago",
      source: "Coface DRA",
    },
    esg: {
      score: 74,
      grade: "B",
      environmental: 78,
      social: 72,
      governance: 73,
      eudrCompliant: true,
      csdddStatus: "In Progress",
      lksgStatus: "Compliant",
      csrdStatus: "In Progress",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "10.3kt CO₂e",
      lastAudit: "Jun 2025",
    },
    resiliency: {
      overall: 6.8,
      transparency: 7.1,
      network: 6.5,
      continuity: 6.9,
      performance: 7.0,
      maturity: 6.5,
      lastUpdated: "Q3 2025",
    },
    alerts: [{ id: "al-gfp-1", type: "logistics", text: "Polymer raw material shortage delaying pipe fittings order GFP-2241", date: "2025-09-29" }],
  },
  {
    id: "dbs",
    name: "DB Schenker",
    ticker: undefined,
    website: "https://www.dbschenker.com",
    countryCode: "DE",
    riskHistory: [19, 20, 20, 21, 21, 20, 20, 21, 21, 21, 20, 21],
    tier: 1,
    category: "Logistics",
    categoryConfidence: "High",
    region: "EU",
    duns: "61-334-8891",
    riskState: "STABLE",
    data: { updatedLabel: "Updated: 1 day ago", confidence: "HIGH" },
    spend: 9.6,
    exposure: 2.8,
    risk: 21,
    onTime: 98,
    qualityPPM: 55,
    creditRisk: {
      friskScore: 9,
      insolvencyProbability: 0.003,
      creditRating: "A+",
      paymentBehavior: "Good",
      bankruptcyRisk12m: "Low",
      lastUpdated: "1 day ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 91,
      grade: "A",
      environmental: 93,
      social: 90,
      governance: 91,
      eudrCompliant: true,
      csdddStatus: "Compliant",
      lksgStatus: "Compliant",
      csrdStatus: "Compliant",
      laborRisk: "Low",
      environmentalRisk: "Low",
      carbonFootprint: "3.9kt CO₂e",
      lastAudit: "Sep 2025",
    },
    resiliency: {
      overall: 9.3,
      transparency: 9.5,
      network: 9.2,
      continuity: 9.4,
      performance: 9.3,
      maturity: 9.1,
      lastUpdated: "Q3 2025",
    },
    alerts: [],
  },
  {
    id: "sen",
    name: "Sensata Technologies",
    ticker: "ST",
    website: "https://www.sensata.com",
    countryCode: "NL",
    riskHistory: [37, 39, 41, 43, 45, 47, 48, 50, 51, 52, 53, 54],
    tier: 2,
    category: "Electronics",
    categoryConfidence: "High",
    region: "NA",
    duns: "78-221-5503",
    riskState: "UNDER OBSERVATION",
    data: { updatedLabel: "Updated: 4 days ago", confidence: "MEDIUM" },
    ratios: { debtToEquity: 1.31, netProfitMargin: 0.082, currentRatio: 1.09 },
    spend: 6.1,
    exposure: 4.7,
    risk: 54,
    onTime: 90,
    qualityPPM: 198,
    creditRisk: {
      friskScore: 5,
      insolvencyProbability: 0.06,
      creditRating: "BB+",
      paymentBehavior: "Moderate",
      bankruptcyRisk12m: "Moderate",
      lastUpdated: "4 days ago",
      source: "CreditRiskMonitor FRISK",
    },
    esg: {
      score: 63,
      grade: "C",
      environmental: 60,
      social: 65,
      governance: 64,
      eudrCompliant: "In Progress",
      csdddStatus: "In Progress",
      lksgStatus: "In Progress",
      csrdStatus: "Not Started",
      laborRisk: "Low",
      environmentalRisk: "Medium",
      carbonFootprint: "15.7kt CO₂e",
      lastAudit: "May 2025",
    },
    resiliency: {
      overall: 6.1,
      transparency: 6.4,
      network: 5.8,
      continuity: 6.2,
      performance: 6.3,
      maturity: 5.8,
      lastUpdated: "Q3 2025",
    },
    alerts: [{ id: "al-sen-1", type: "risk", text: "US tariff exposure elevated — sensor component import duty increase", date: "2025-09-30" }],
  },
];

// ── Contracts ─────────────────────────────────────────────────────────────────
export const CONTRACTS: Contract[] = [
  { id: "co-01", supplierId: "sit", supplierName: "SIT Group", title: "GAS-CTRL-MSA-2023", type: "Master Services", expires: "2025-12-15", value: "£18.4M", status: "Under Renegotiation", autoRenew: false },
  { id: "co-02", supplierId: "ebm", supplierName: "Ebm-papst", title: "FAN-MOTOR-SLA-2024", type: "Supply & Service", expires: "2026-03-31", value: "£11.7M", status: "Active", autoRenew: true },
  { id: "co-03", supplierId: "gru", supplierName: "Grundfos", title: "PUMP-FRAME-2024", type: "Framework", expires: "2026-06-30", value: "£16.2M", status: "Active", autoRenew: true },
  { id: "co-04", supplierId: "aal", supplierName: "Aalberts Industries", title: "FLOW-CTRL-LTA-2022", type: "Long-term Agreement", expires: "2025-11-01", value: "£8.3M", status: "Pending Renewal", autoRenew: false },
  { id: "co-05", supplierId: "dbs", supplierName: "DB Schenker", title: "LOG-EU-FRAME-24", type: "Framework", expires: "2026-09-30", value: "£9.6M", status: "Active", autoRenew: true },
  { id: "co-06", supplierId: "dan", supplierName: "Danfoss", title: "VALVE-QPA-2024", type: "Quality & Price", expires: "2025-10-31", value: "£7.4M", status: "Pending Renewal", autoRenew: false },
  { id: "co-07", supplierId: "sen", supplierName: "Sensata Technologies", title: "SENSOR-MSA-2023", type: "Master Services", expires: "2026-02-28", value: "£6.1M", status: "Active", autoRenew: false },
];

// ── Global Alerts ─────────────────────────────────────────────────────────────
export const GLOBAL_ALERTS: GlobalAlert[] = [
  { id: "ga-01", supplierId: "aal", text: "Aalberts Industries risk escalated — credit downgrade and earnings miss", type: "risk", date: "1d ago" },
  { id: "ga-02", supplierId: "sit", text: "SIT Group observation window — Day 34/90 checkpoint due", type: "observation", date: "2d ago" },
  { id: "ga-03", supplierId: "dan", text: "Danfoss VALVE-QPA-2024 contract renewal window open (30 days remaining)", type: "contract", date: "3d ago" },
  { id: "ga-04", supplierId: "ebm", text: "Fan motor lead times extended — 14-week backlog at Ebm-papst Mulfingen plant", type: "logistics", date: "5d ago" },
];

// ── Live Disruption Events ────────────────────────────────────────────────────
export const LIVE_EVENTS: LiveEvent[] = [
  {
    id: "ev-001",
    category: "financial",
    severity: "critical",
    title: "Aalberts Industries — Credit Downgrade & Earnings Miss",
    detail: "Moody's downgraded Aalberts Industries to B following a 22% H1 EBITDA miss. Liquidity ratio fell to 0.71. Risk of supply disruption to flow control components is elevated. Secondary source qualification initiated.",
    region: "EU",
    country: "Netherlands",
    affectedSupplierIds: ["aal"],
    estimatedImpact: "£9.4M exposure at risk",
    date: "1d ago",
    source: "Moody's / CreditRiskMonitor",
    status: "Active",
  },
  {
    id: "ev-002",
    category: "labor",
    severity: "high",
    title: "German Manufacturing — IG Metall Strike Action",
    detail: "IG Metall initiated rolling strike action across Baden-Württemberg manufacturing plants over wage negotiations. Ebm-papst Mulfingen facility affected with partial production suspension.",
    region: "EU",
    country: "Germany",
    affectedSupplierIds: ["ebm"],
    estimatedImpact: "£2.4M revenue at risk",
    leadTimeExtension: "3–6 weeks",
    date: "3d ago",
    source: "IG Metall / Reuters",
    status: "Active",
  },
  {
    id: "ev-003",
    category: "logistics",
    severity: "high",
    title: "Port of Rotterdam — Customs IT System Outage",
    detail: "Dutch customs authority Douane experiencing extended system outage. Manual processing causing 4–7 day clearance delays at Europe's largest container port, impacting EU-UK freight lanes.",
    region: "EU",
    country: "Netherlands",
    affectedSupplierIds: ["gru", "dan", "gfp", "dbs"],
    estimatedImpact: "£1.8M delay costs",
    leadTimeExtension: "4–7 days",
    date: "2d ago",
    source: "Port of Rotterdam / Douane",
    status: "Monitoring",
  },
  {
    id: "ev-004",
    category: "regulatory",
    severity: "high",
    title: "EU CSDDD — Q4 2025 Enforcement Deadline",
    detail: "The EU Corporate Sustainability Due Diligence Directive enters full enforcement for companies with >500 employees. Worcester Bosch must demonstrate Tier 1 and Tier 2 supplier compliance across human rights and environmental due diligence.",
    region: "EU",
    country: "EU-wide",
    affectedSupplierIds: ["sit", "aal", "gfp", "sen"],
    estimatedImpact: "Regulatory penalty exposure",
    date: "5d ago",
    source: "European Commission",
    status: "Monitoring",
  },
  {
    id: "ev-005",
    category: "financial",
    severity: "high",
    title: "SIT Group — FRISK Score Decline",
    detail: "SIT Group's FRISK score declined from 5 to 3, signalling elevated financial stress. Working capital deterioration driven by lower gas appliance demand across Southern Europe. Observation window remains active.",
    region: "EU",
    country: "Italy",
    affectedSupplierIds: ["sit"],
    estimatedImpact: "£7.2M exposure",
    date: "2d ago",
    source: "CreditRiskMonitor FRISK",
    status: "Active",
  },
  {
    id: "ev-006",
    category: "regulatory",
    severity: "medium",
    title: "UK Boiler Plus Regulation — Gas Control Specification Update",
    detail: "UK government updated Boiler Plus technical specifications for gas controls. New modulation and interlock requirements take effect Q1 2026. SIT Group and Ebm-papst components require re-validation testing.",
    region: "EU",
    country: "United Kingdom",
    affectedSupplierIds: ["sit", "ebm"],
    estimatedImpact: "Re-qualification cost £0.4M",
    date: "6d ago",
    source: "BEIS / Boiler Plus Technical Guidance",
    status: "Monitoring",
  },
  {
    id: "ev-007",
    category: "logistics",
    severity: "medium",
    title: "US Tariff Increase — Electronic Sensor Imports",
    detail: "US Trade Representative imposed additional 15% tariff on imported electronic sensors and pressure transducers. Sensata Technologies manufacturing costs elevated; price renegotiation expected at next contract review.",
    region: "NA",
    country: "United States",
    affectedSupplierIds: ["sen"],
    estimatedImpact: "£0.9M cost increase annually",
    date: "4d ago",
    source: "USTR / Federal Register",
    status: "Active",
  },
  {
    id: "ev-008",
    category: "quality",
    severity: "low",
    title: "Georg Fischer — Polymer Fitting Batch Non-Conformance",
    detail: "Batch GFP-2241 of polymer pipe fittings failed pressure tolerance testing at 4.2% above deviation threshold. Batch quarantined pending root cause analysis. Replacement order estimated 6-week lead time.",
    region: "EU",
    country: "Switzerland",
    affectedSupplierIds: ["gfp"],
    estimatedImpact: "£0.3M quarantine cost",
    date: "7d ago",
    source: "Internal QMS",
    status: "Active",
  },
];

// ── Shipments ─────────────────────────────────────────────────────────────────
export const SHIPMENTS: Shipment[] = [
  { id: "SHP-4401", supplierId: "sit", origin: "Padova, IT", destination: "Worcester, UK", carrier: "DB Schenker Road", eta: "Oct 18, 2025", delayRisk: "Low", status: "On Track", value: "£1.6M" },
  { id: "SHP-4412", supplierId: "aal", origin: "Utrecht, NL", destination: "Worcester, UK", carrier: "DHL Freight", eta: "Oct 21, 2025", delayDays: 7, delayRisk: "High", status: "Delayed", value: "£0.9M" },
  { id: "SHP-4428", supplierId: "gru", origin: "Bjerringbro, DK", destination: "Felixstowe, UK", carrier: "Maersk", eta: "Oct 15, 2025", delayRisk: "Low", status: "On Track", value: "£2.2M" },
  { id: "SHP-4437", supplierId: "ebm", origin: "Mulfingen, DE", destination: "Worcester, UK", carrier: "DB Schenker Road", eta: "Oct 23, 2025", delayDays: 4, delayRisk: "Medium", status: "At Risk", value: "£1.1M" },
  { id: "SHP-4449", supplierId: "gfp", origin: "Schaffhausen, CH", destination: "Felixstowe, UK", carrier: "Kuehne+Nagel", eta: "Oct 19, 2025", delayRisk: "Low", status: "On Track", value: "£0.6M" },
  { id: "SHP-4461", supplierId: "sen", origin: "Attleboro, MA", destination: "Southampton, UK", carrier: "FedEx International", eta: "Oct 26, 2025", delayDays: 5, delayRisk: "High", status: "Customs Hold", value: "£0.8M" },
  { id: "SHP-4472", supplierId: "dan", origin: "Nordborg, DK", destination: "Worcester, UK", carrier: "DSV Road", eta: "Oct 16, 2025", delayRisk: "Low", status: "On Track", value: "£0.7M" },
];

// ── Crisis Rooms ──────────────────────────────────────────────────────────────
export const CRISIS_ROOMS: CrisisRoom[] = [
  {
    id: "cr-001",
    title: "Aalberts Industries — Financial Escalation",
    triggeredBy: "ev-001",
    severity: "critical",
    openedDate: "Oct 02, 2025",
    owner: "Sarah Renwick",
    affectedSupplierIds: ["aal"],
    affectedParts: ["Flow Control Valve FCV-220", "Hydronic Manifold HM-08", "Pressure Balancing Unit PBU-14"],
    estimatedExposure: "£9.4M",
    status: "Open",
    actions: [
      { id: "a1", text: "Initiate secondary source qualification for FCV-220 — Giacomini or Watts Water Technologies", owner: "M. Hennessy — Procurement", due: "Oct 10", done: false },
      { id: "a2", text: "Increase safety stock for flow control valves to 45-day buffer", owner: "J. Haines — Ops", due: "Oct 08", done: true },
      { id: "a3", text: "Legal review: trigger MAC clause in FLOW-CTRL-LTA-2022 if FRISK < 2", owner: "Legal", due: "Oct 12", done: false },
      { id: "a4", text: "Notify production planning — potential FCV-220 shortage from Week 46", owner: "T. Bray — Planning", due: "Oct 07", done: true },
    ],
  },
  {
    id: "cr-002",
    title: "SIT Group — Observation Window Active",
    triggeredBy: "ev-005",
    severity: "high",
    openedDate: "Sep 20, 2025",
    owner: "A. Patel",
    affectedSupplierIds: ["sit"],
    affectedParts: ["Gas Valve GV-410", "Safety Solenoid SS-22", "Modulating Gas Valve MGV-8"],
    estimatedExposure: "£7.2M",
    status: "Open",
    actions: [
      { id: "b1", text: "Weekly FRISK score monitoring — escalate if score drops to 2", owner: "A. Patel — Risk", due: "Ongoing", done: false },
      { id: "b2", text: "Pre-qualify Orkli as backup gas controls supplier for GV-410", owner: "M. Hennessy — Procurement", due: "Oct 20", done: false },
      { id: "b3", text: "Extend SIT Group payment terms to net-90 to ease their cash flow", owner: "Finance", due: "Sep 18", done: true },
      { id: "b4", text: "30-day safety stock build for GV-410 and SS-22 critical SKUs", owner: "J. Haines — Ops", due: "Oct 05", done: true },
    ],
  },
  {
    id: "cr-003",
    title: "Ebm-papst — IG Metall Strike Disruption",
    triggeredBy: "ev-002",
    severity: "high",
    openedDate: "Oct 07, 2025",
    owner: "D. Okafor",
    affectedSupplierIds: ["ebm"],
    affectedParts: ["Flue Fan FF-3000", "Air Pressure Switch APS-14", "Variable Speed Fan VSF-2"],
    estimatedExposure: "£2.4M",
    status: "Contained",
    actions: [
      { id: "c1", text: "Confirm production resumption ETA from Mulfingen plant", owner: "M. Hennessy — Procurement", due: "Oct 09", done: true },
      { id: "c2", text: "Draw down safety stock FF-3000 — 21-day buffer available", owner: "J. Haines — Ops", due: "Oct 08", done: true },
      { id: "c3", text: "Evaluate Ziehl-Abegg as short-term alternate for FF-3000", owner: "M. Hennessy — Procurement", due: "Oct 15", done: false },
    ],
  },
];

export const suppliersAll: Supplier[] = [
  ...suppliersGoverned,
  ...suppliersDirectory.filter((s) => !suppliersGoverned.find((g) => g.id === s.id)),
].map((s) => ({ ...s, risk: computeRisk(s) }));

// ── Recovery Profiles (TTR / TTS per supplier) ────────────────────────────────
export const RECOVERY_PROFILES: Record<string, RecoveryProfile> = {
  sit: {
    inventoryBufferDays: 18,
    timeToSurvive: 18,
    timeToRecover: 90,
    criticalComponents: ["Gas Control Valve GCV-2200", "Thermocouple TC-44", "SIT Gas Valve Block"],
    affectedProductLines: ["Greenstar 4 Life", "Greenstar 8000 Life"],
    alternativeQualified: false,
    safetyStockRecommendation: 45,
    lastReviewed: "Oct 2025",
  },
  ebm: {
    inventoryBufferDays: 45,
    timeToSurvive: 45,
    timeToRecover: 120,
    criticalComponents: ["Flue Fan FF-3000", "Variable Speed Fan VSF-2", "Air Pressure Switch APS-14"],
    affectedProductLines: ["Greenstar 4 Life", "Greenstar 8000 Life", "Greenwave Heat Pump"],
    alternativeQualified: false,
    safetyStockRecommendation: 60,
    lastReviewed: "Sep 2025",
  },
  aal: {
    inventoryBufferDays: 22,
    timeToSurvive: 22,
    timeToRecover: 75,
    criticalComponents: ["Flow Control Valve FCV-110", "Brass Manifold BM-44", "Pressure Regulator PR-22"],
    affectedProductLines: ["Greenstar 4 Life", "Greenwave Heat Pump"],
    alternativeQualified: false,
    safetyStockRecommendation: 35,
    lastReviewed: "Oct 2025",
  },
  gru: {
    inventoryBufferDays: 60,
    timeToSurvive: 60,
    timeToRecover: 90,
    criticalComponents: ["Circulation Pump UP15-14", "Pump Head Assembly PHA-3"],
    affectedProductLines: ["Greenstar 4 Life", "Greenstar 8000 Life"],
    alternativeQualified: true,
    safetyStockRecommendation: 45,
    lastReviewed: "Aug 2025",
  },
  dan: {
    inventoryBufferDays: 35,
    timeToSurvive: 35,
    timeToRecover: 60,
    criticalComponents: ["3-Port Zone Valve ZV-3", "Motorised Valve MV-22", "DHW Valve Assembly"],
    affectedProductLines: ["Greenstar 8000 Life", "Greenwave Heat Pump"],
    alternativeQualified: true,
    safetyStockRecommendation: 30,
    lastReviewed: "Sep 2025",
  },
  gfp: {
    inventoryBufferDays: 12,
    timeToSurvive: 12,
    timeToRecover: 45,
    criticalComponents: ["Stainless Pipe Fitting PF-220", "Compression Fitting CF-18", "Threaded Elbow TE-15"],
    affectedProductLines: ["Greenstar 4 Life", "Greenstar 8000 Life", "Greenwave Heat Pump"],
    alternativeQualified: false,
    safetyStockRecommendation: 30,
    lastReviewed: "Oct 2025",
  },
  dbs: {
    inventoryBufferDays: 7,
    timeToSurvive: 7,
    timeToRecover: 14,
    criticalComponents: ["EU-UK Freight Lanes", "Customs Brokerage", "Cross-Channel Logistics"],
    affectedProductLines: ["All product lines"],
    alternativeQualified: true,
    safetyStockRecommendation: 14,
    lastReviewed: "Oct 2025",
  },
  sen: {
    inventoryBufferDays: 28,
    timeToSurvive: 28,
    timeToRecover: 55,
    criticalComponents: ["Flame Sensor FS-44", "Pressure Sensor PS-12", "Temperature Sensor TS-88"],
    affectedProductLines: ["Greenstar 4 Life", "Greenstar 8000 Life"],
    alternativeQualified: false,
    safetyStockRecommendation: 40,
    lastReviewed: "Sep 2025",
  },
};

// ── Certifications per supplier ───────────────────────────────────────────────
export const CERTIFICATIONS: Record<string, Certification[]> = {
  sit: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "Bureau Veritas", issued: "2022-03-15", expires: "2025-03-14", status: "Expiring Soon", scope: "Gas control components design & manufacture" },
    { name: "PED 2014/68/EU", standard: "PED", issuer: "TÜV Rheinland", issued: "2023-01-10", expires: "2026-01-09", status: "Valid", scope: "Pressure Equipment Directive — gas valves" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "DNV GL", issued: "2021-06-20", expires: "2024-06-19", status: "In Renewal", scope: "Environmental management" },
  ],
  ebm: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "TÜV SÜD", issued: "2023-05-01", expires: "2026-04-30", status: "Valid", scope: "EC motors and fan systems" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "TÜV SÜD", issued: "2023-05-01", expires: "2026-04-30", status: "Valid" },
    { name: "IATF 16949:2016", standard: "IATF 16949", issuer: "TÜV SÜD", issued: "2022-09-01", expires: "2025-08-31", status: "Expiring Soon", scope: "Automotive-grade quality management" },
  ],
  aal: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "Bureau Veritas", issued: "2020-11-01", expires: "2023-10-31", status: "Expired", scope: "Flow control & pipe systems" },
    { name: "ISO 45001:2018", standard: "ISO 45001", issuer: "Lloyd's Register", issued: "2023-02-14", expires: "2026-02-13", status: "Valid", scope: "Occupational health & safety" },
    { name: "PED 2014/68/EU", standard: "PED", issuer: "DNV GL", issued: "2022-07-01", expires: "2025-06-30", status: "Expiring Soon" },
  ],
  gru: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "DNV GL", issued: "2023-01-15", expires: "2026-01-14", status: "Valid" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "DNV GL", issued: "2023-01-15", expires: "2026-01-14", status: "Valid" },
    { name: "EN 13831", standard: "EN 13831", issuer: "TÜV Rheinland", issued: "2024-03-01", expires: "2027-02-28", status: "Valid", scope: "Closed expansion vessels" },
  ],
  dan: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "DNV GL", issued: "2022-08-01", expires: "2025-07-31", status: "Expiring Soon" },
    { name: "ISO 50001:2018", standard: "ISO 50001", issuer: "SGS", issued: "2023-04-01", expires: "2026-03-31", status: "Valid", scope: "Energy management" },
    { name: "PED 2014/68/EU", standard: "PED", issuer: "Bureau Veritas", issued: "2024-01-01", expires: "2027-01-01", status: "Valid" },
  ],
  gfp: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "SGS", issued: "2023-10-01", expires: "2026-09-30", status: "Valid" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "SGS", issued: "2023-10-01", expires: "2026-09-30", status: "Valid" },
  ],
  dbs: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "Bureau Veritas", issued: "2024-01-01", expires: "2027-01-01", status: "Valid", scope: "Transport & logistics operations" },
    { name: "ISO 28000:2022", standard: "ISO 28000", issuer: "Lloyd's Register", issued: "2024-06-01", expires: "2027-05-31", status: "Valid", scope: "Supply chain security management" },
    { name: "AEO-F", standard: "AEO", issuer: "HMRC / German Customs", issued: "2019-03-01", expires: "2027-03-01", status: "Valid", scope: "Authorised Economic Operator — Full" },
  ],
  sen: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "TÜV SÜD", issued: "2022-06-01", expires: "2025-05-31", status: "Expiring Soon" },
    { name: "IATF 16949:2016", standard: "IATF 16949", issuer: "TÜV SÜD", issued: "2023-02-01", expires: "2026-01-31", status: "Valid" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "TÜV SÜD", issued: "2022-06-01", expires: "2025-05-31", status: "Expiring Soon" },
  ],
};

// ── Product Lines / BOM Risk ──────────────────────────────────────────────────
export const PRODUCT_LINES: ProductLine[] = [
  {
    id: "gs4",
    name: "Greenstar 4 Life",
    model: "GS4L-24/28/32/36",
    annualVolume: 85000,
    bomItems: [
      { partNumber: "GCV-2200", partName: "Gas Control Valve", supplierId: "sit", quantity: 1, unitCost: 42, leadTimeDays: 18, soloSourced: true, riskScore: 64 },
      { partNumber: "FF-3000", partName: "Flue Fan Assembly", supplierId: "ebm", quantity: 1, unitCost: 38, leadTimeDays: 45, soloSourced: true, riskScore: 41 },
      { partNumber: "FCV-110", partName: "Flow Control Valve", supplierId: "aal", quantity: 2, unitCost: 28, leadTimeDays: 22, soloSourced: false, riskScore: 76 },
      { partNumber: "UP15-14", partName: "Circulation Pump", supplierId: "gru", quantity: 1, unitCost: 55, leadTimeDays: 60, soloSourced: false, riskScore: 27 },
      { partNumber: "FS-44", partName: "Flame Sensor", supplierId: "sen", quantity: 1, unitCost: 18, leadTimeDays: 28, soloSourced: false, riskScore: 54 },
      { partNumber: "PF-220", partName: "Stainless Pipe Fitting", supplierId: "gfp", quantity: 8, unitCost: 4.5, leadTimeDays: 12, soloSourced: false, riskScore: 48 },
    ],
  },
  {
    id: "gs8",
    name: "Greenstar 8000 Life",
    model: "GS8L-30/35/40",
    annualVolume: 42000,
    bomItems: [
      { partNumber: "GCV-2200", partName: "Gas Control Valve", supplierId: "sit", quantity: 1, unitCost: 48, leadTimeDays: 18, soloSourced: true, riskScore: 64 },
      { partNumber: "VSF-2", partName: "Variable Speed Fan", supplierId: "ebm", quantity: 1, unitCost: 62, leadTimeDays: 45, soloSourced: true, riskScore: 41 },
      { partNumber: "ZV-3", partName: "3-Port Zone Valve", supplierId: "dan", quantity: 2, unitCost: 34, leadTimeDays: 35, soloSourced: false, riskScore: 31 },
      { partNumber: "BM-44", partName: "Brass Manifold", supplierId: "aal", quantity: 1, unitCost: 85, leadTimeDays: 22, soloSourced: false, riskScore: 76 },
      { partNumber: "PS-12", partName: "Pressure Sensor", supplierId: "sen", quantity: 2, unitCost: 24, leadTimeDays: 28, soloSourced: false, riskScore: 54 },
    ],
  },
  {
    id: "gwv",
    name: "Greenwave Heat Pump",
    model: "GWV-5/8/12/16kW",
    annualVolume: 18000,
    bomItems: [
      { partNumber: "MV-22", partName: "Motorised Valve", supplierId: "dan", quantity: 3, unitCost: 44, leadTimeDays: 35, soloSourced: false, riskScore: 31 },
      { partNumber: "FCV-110", partName: "Flow Control Valve", supplierId: "aal", quantity: 3, unitCost: 28, leadTimeDays: 22, soloSourced: false, riskScore: 76 },
      { partNumber: "VSF-2", partName: "Variable Speed Fan", supplierId: "ebm", quantity: 2, unitCost: 62, leadTimeDays: 45, soloSourced: true, riskScore: 41 },
      { partNumber: "CF-18", partName: "Compression Fitting", supplierId: "gfp", quantity: 12, unitCost: 3.8, leadTimeDays: 12, soloSourced: false, riskScore: 48 },
      { partNumber: "TS-88", partName: "Temperature Sensor", supplierId: "sen", quantity: 4, unitCost: 15, leadTimeDays: 28, soloSourced: false, riskScore: 54 },
    ],
  },
];

// ── Commodity Prices ──────────────────────────────────────────────────────────
export const COMMODITIES: CommodityPrice[] = [
  {
    id: "steel",
    name: "Steel (HRC)",
    unit: "tonne",
    currentPrice: 845,
    currency: "EUR",
    priceHistory: [740, 780, 820, 890, 920, 880, 860, 840, 845],
    changePercent: 0.6,
    trend: "Stable",
    volatility: "Medium",
    affectedCategories: ["Components", "Raw Materials"],
    affectedSupplierIds: ["aal", "gfp"],
    alert: undefined,
  },
  {
    id: "copper",
    name: "Copper",
    unit: "tonne",
    currentPrice: 7250,
    currency: "EUR",
    priceHistory: [6800, 7200, 7450, 7800, 7650, 7500, 7200, 6950, 7250],
    changePercent: 4.3,
    trend: "Rising",
    volatility: "High",
    affectedCategories: ["Electronics", "Components"],
    affectedSupplierIds: ["sen", "sit", "dan"],
    alert: "Copper +4.3% QoQ — sensor and valve cost pressure expected",
  },
  {
    id: "aluminium",
    name: "Aluminium",
    unit: "tonne",
    currentPrice: 2130,
    currency: "EUR",
    priceHistory: [1980, 2050, 2100, 2200, 2180, 2120, 2080, 2050, 2130],
    changePercent: 3.9,
    trend: "Rising",
    volatility: "Medium",
    affectedCategories: ["Components"],
    affectedSupplierIds: ["ebm", "aal"],
    alert: "Aluminium rising — EC motor casing cost up ~3.9% QoQ",
  },
  {
    id: "natural-gas",
    name: "Natural Gas (TTF)",
    unit: "MWh",
    currentPrice: 38.4,
    currency: "EUR",
    priceHistory: [28, 32, 45, 62, 58, 42, 35, 31, 38.4],
    changePercent: 23.9,
    trend: "Rising",
    volatility: "High",
    affectedCategories: ["Components", "Logistics"],
    affectedSupplierIds: ["sit", "gfp", "dbs"],
    alert: "TTF gas +24% — energy-intensive suppliers facing margin pressure",
  },
  {
    id: "rare-earth",
    name: "Rare Earth Index",
    unit: "index",
    currentPrice: 158,
    currency: "USD",
    priceHistory: [130, 138, 142, 148, 162, 175, 168, 155, 158],
    changePercent: -4.2,
    trend: "Falling",
    volatility: "High",
    affectedCategories: ["Electronics"],
    affectedSupplierIds: ["sen", "ebm"],
    alert: undefined,
  },
  {
    id: "stainless",
    name: "Stainless Steel (316L)",
    unit: "tonne",
    currentPrice: 2840,
    currency: "EUR",
    priceHistory: [2400, 2520, 2650, 2780, 2900, 2870, 2820, 2790, 2840],
    changePercent: 1.8,
    trend: "Stable",
    volatility: "Low",
    affectedCategories: ["Raw Materials", "Components"],
    affectedSupplierIds: ["gfp", "aal"],
    alert: undefined,
  },
];

// ── Supplier Self-Assessments ─────────────────────────────────────────────────
export const ASSESSMENTS: Assessment[] = [
  { supplierId: "sit",  supplierName: "SIT Group",            templateId: "fin-health", templateName: "Financial Health Check",          sentDate: "Sep 15, 2025", dueDate: "Sep 30, 2025", completedDate: "Oct 02, 2025", status: "Completed",  completionPct: 100, riskFlags: 4 },
  { supplierId: "aal",  supplierName: "Aalberts Industries",  templateId: "single-src", templateName: "Single Source Dependency Review",  sentDate: "Oct 01, 2025", dueDate: "Oct 15, 2025", status: "In Progress", completionPct: 60, riskFlags: 2 },
  { supplierId: "ebm",  supplierName: "Ebm-papst",            templateId: "dis-rec",   templateName: "Disaster Recovery Assessment",     sentDate: "Oct 05, 2025", dueDate: "Oct 20, 2025", status: "Overdue",    completionPct: 25, riskFlags: 0 },
  { supplierId: "gfp",  supplierName: "Georg Fischer",        templateId: "sub-tier",  templateName: "Sub-tier Disclosure Questionnaire", sentDate: "Oct 10, 2025", dueDate: "Oct 25, 2025", status: "Sent",       completionPct: 0,  riskFlags: 0 },
  { supplierId: "gru",  supplierName: "Grundfos",             templateId: "fin-health", templateName: "Financial Health Check",          status: "Not Sent",   completionPct: 0,  riskFlags: 0 },
  { supplierId: "dan",  supplierName: "Danfoss",              templateId: "dis-rec",   templateName: "Disaster Recovery Assessment",     status: "Not Sent",   completionPct: 0,  riskFlags: 0 },
  { supplierId: "dbs",  supplierName: "DB Schenker",          templateId: "single-src", templateName: "Single Source Dependency Review", status: "Not Sent",   completionPct: 0,  riskFlags: 0 },
  { supplierId: "sen",  supplierName: "Sensata Technologies", templateId: "sub-tier",  templateName: "Sub-tier Disclosure Questionnaire", status: "Not Sent",   completionPct: 0,  riskFlags: 0 },
];

// ── Industry Benchmarks ───────────────────────────────────────────────────────
export const BENCHMARKS: IndustryBenchmark[] = [
  { sector: "HVAC & Heating (Your Portfolio)", avgRiskScore: 46, avgDPS: 42, avgOnTime: 91, avgESGScore: 68, sampleSize: 8 },
  { sector: "HVAC & Heating Industry Average", avgRiskScore: 48, avgDPS: 45, avgOnTime: 93, avgESGScore: 65, sampleSize: 214 },
  { sector: "Industrial Components (EU)",       avgRiskScore: 52, avgDPS: 49, avgOnTime: 91, avgESGScore: 62, sampleSize: 1840 },
  { sector: "Automotive Supply Chain",          avgRiskScore: 58, avgDPS: 54, avgOnTime: 96, avgESGScore: 71, sampleSize: 3200 },
  { sector: "Logistics & Transport",            avgRiskScore: 31, avgDPS: 28, avgOnTime: 97, avgESGScore: 58, sampleSize: 680 },
];

// ── Live Data Feeds ───────────────────────────────────────────────────────────
export const DATA_FEEDS: DataFeed[] = [
  { name: "Dun & Bradstreet",    shortName: "D&B",      type: "Financial", lastRefreshed: "2h ago",  status: "Live",    recordsUpdated: 3 },
  { name: "S&P Global",          shortName: "S&P",      type: "Credit",    lastRefreshed: "6h ago",  status: "Live",    recordsUpdated: 1 },
  { name: "Moody's Analytics",   shortName: "Moody's",  type: "Credit",    lastRefreshed: "12h ago", status: "Live",    recordsUpdated: 2 },
  { name: "Prewave",             shortName: "Prewave",  type: "ESG",       lastRefreshed: "1h ago",  status: "Live",    recordsUpdated: 5 },
  { name: "Everstream Analytics",shortName: "ESA",      type: "Events",    lastRefreshed: "15m ago", status: "Live",    recordsUpdated: 8 },
  { name: "project44",           shortName: "p44",      type: "Logistics", lastRefreshed: "5m ago",  status: "Live",    recordsUpdated: 4 },
  { name: "LME / Platts",        shortName: "LME",      type: "Financial", lastRefreshed: "4h ago",  status: "Live",    recordsUpdated: 6 },
];

// ══════════════════════════════════════════════════════════════════════════════
// ── US GENERIC MODE DATA  (Meridian Industrial Group, Chicago IL) ─────────────
// ── Shown when URL does NOT contain ?client=wb ────────────────────────────────
// ══════════════════════════════════════════════════════════════════════════════

export const suppliersGovernedUS: Supplier[] = [
  // ── Flex Ltd. — HIGH RISK · ESCALATED ──────────────────────────────────────
  {
    id: "flx", name: "Flex Ltd.", ticker: "FLEX",
    website: "https://flex.com",
    countryCode: "SG", region: "APAC", tier: 1,
    category: "Electronics", categoryConfidence: "High",
    spend: 14.2, exposure: 6.8, risk: 68,
    onTime: 89, qualityPPM: 224, riskState: "ESCALATED",
    riskHistory: [38, 42, 45, 49, 52, 55, 57, 59, 62, 64, 66, 68],
    data: { updatedLabel: "Updated: 2 days ago", confidence: "MEDIUM" },
    ratios: { debtToEquity: 1.68, netProfitMargin: 0.032, currentRatio: 1.08 },
    financialHealth: {
      score: 32,
      dioTrend: [58, 64, 72, 81],
      dsoTrend: [44, 48, 54, 59],
      dpoCurrent: 62,
      cccTrend: [40, 50, 64, 78],
      inventoryGrowthYoY: 0.22,
      revenueGrowthYoY: -0.12,
      netDebtEbitda: [2.4, 2.7, 3.0, 3.3, 3.6, 3.9, 4.1, 4.3],
      interestCoverage: 2.1,
      capexToDepreciation: [1.05, 0.91, 0.77, 0.68],
      flags: [
        { type: "revenue", severity: "critical", text: "Revenue -12% vs guidance — EBITDA margin fell to 3.2% on program delays and cost inflation" },
        { type: "inventory", severity: "warn", text: "Inventory +22% while revenue declining — build-up signals demand shortfall" },
        { type: "dso", severity: "warn", text: "DSO expanded 44 → 59 days — receivables collection slowing" },
        { type: "leverage", severity: "warn", text: "Net Debt/EBITDA at 4.3× — elevated and trending above 4× threshold" },
      ],
    },
    duns: "08-773-4412",
    creditRisk: { friskScore: 4, insolvencyProbability: 0.08, creditRating: "BB", paymentBehavior: "Moderate", bankruptcyRisk12m: "Moderate", lastUpdated: "2 days ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 58, grade: "C", environmental: 55, social: 60, governance: 58, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Under Review", scope3Status: "In Progress", conflictMineralsStatus: "Compliant", laborRisk: "High", environmentalRisk: "Medium", carbonFootprint: "22.4kt CO₂e", lastAudit: "Mar 2025" },
    resiliency: { overall: 5.8, transparency: 5.4, network: 5.6, continuity: 6.0, performance: 5.8, maturity: 6.2, lastUpdated: "Q2 2025" },
    alerts: [
      { id: "al-flx-1", type: "risk", text: "FRISK score declined to 4 — Q2 earnings miss, margin compression", date: "2025-10-02" },
      { id: "al-flx-2", type: "logistics", text: "PCB assembly lead times extended to 16 weeks — component allocation shortfall", date: "2025-09-28" },
    ],
    timeline: [
      { date: "Sep 10, 2025", text: "Q2 earnings call — revenue guidance cut 12%, EBITDA margin fell to 3.2%" },
      { date: "Sep 22, 2025", text: "Procurement escalated to VP Supply Chain — secondary source evaluation initiated" },
      { date: "Oct 02, 2025", text: "FRISK score declined from 6 to 4 — risk state escalated" },
    ],
  },
  // ── Zhonghe Precision — HIGH RISK · UFLPA · ESCALATED ──────────────────────
  {
    id: "zhp", name: "Zhonghe Precision", ticker: undefined,
    website: undefined,
    countryCode: "CN", region: "APAC", tier: 2,
    category: "Electronics", categoryConfidence: "Medium",
    spend: 4.8, exposure: 4.2, risk: 78,
    onTime: 85, qualityPPM: 312, riskState: "ESCALATED",
    riskHistory: [55, 58, 60, 63, 65, 67, 69, 71, 73, 75, 77, 78],
    data: { updatedLabel: "Updated: 5 days ago", confidence: "LOW" },
    ratios: undefined,
    duns: undefined,
    creditRisk: { friskScore: 3, insolvencyProbability: 0.11, creditRating: "NR", paymentBehavior: "Poor", bankruptcyRisk12m: "High", lastUpdated: "5 days ago", source: "Coface DRA" },
    esg: { score: 28, grade: "F", environmental: 25, social: 30, governance: 28, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Non-Compliant", scope3Status: "Not Started", conflictMineralsStatus: "Non-Compliant", laborRisk: "High", environmentalRisk: "High", lastAudit: undefined },
    resiliency: { overall: 3.2, transparency: 2.8, network: 3.0, continuity: 3.4, performance: 3.2, maturity: 3.6, lastUpdated: "Q1 2025" },
    alerts: [
      { id: "al-zhp-1", type: "risk", text: "UFLPA enforcement — shipment detained at Port of Long Beach pending forced labor review", date: "2025-10-01" },
      { id: "al-zhp-2", type: "quality", text: "Batch ZHP-8821 failed incoming inspection — PPM rate 312, exceeds 250 threshold", date: "2025-09-25" },
    ],
    timeline: [
      { date: "Sep 18, 2025", text: "CBP initiated UFLPA review on Xinjiang-region component sourcing" },
      { date: "Oct 01, 2025", text: "Shipment SHP-US-4419 detained at Long Beach — $1.8M value at risk" },
      { date: "Oct 03, 2025", text: "Procurement engaged trade compliance counsel — alternative sourcing underway" },
    ],
  },
  // ── Haynes International — MEDIUM RISK · UNDER OBSERVATION ─────────────────
  {
    id: "hay", name: "Haynes International", ticker: "HAYN",
    website: "https://www.haynesintl.com",
    countryCode: "US", region: "NA", tier: 2,
    category: "Raw Materials", categoryConfidence: "High",
    spend: 5.6, exposure: 3.4, risk: 52,
    onTime: 91, qualityPPM: 198, riskState: "UNDER OBSERVATION",
    riskHistory: [38, 40, 41, 43, 44, 46, 47, 48, 49, 50, 51, 52],
    data: { updatedLabel: "Updated: 6 days ago", confidence: "MEDIUM" },
    ratios: { debtToEquity: 0.82, netProfitMargin: 0.061, currentRatio: 1.22 },
    financialHealth: {
      score: 48,
      dioTrend: [46, 49, 53, 57],
      dsoTrend: [40, 42, 44, 46],
      dpoCurrent: 48,
      cccTrend: [38, 43, 49, 55],
      inventoryGrowthYoY: 0.16,
      revenueGrowthYoY: -0.04,
      netDebtEbitda: [1.4, 1.5, 1.7, 1.9, 2.1, 2.2, 2.3, 2.4],
      interestCoverage: 4.8,
      capexToDepreciation: [1.18, 1.14, 1.09, 1.05],
      flags: [
        { type: "margin", severity: "warn", text: "Net margin compressed to 6.1% — nickel/cobalt input costs +18% YTD squeezing alloy margins" },
        { type: "inventory", severity: "warn", text: "Inventory +16% on flat/declining revenue — safety stock building ahead of cost escalation" },
        { type: "ccc", severity: "info", text: "Cash Conversion Cycle lengthening: 38 → 55 days — modest working capital pressure" },
      ],
    },
    duns: "07-441-2231",
    observation: { day: 28, total: 90, progressPct: 31 },
    checklist: { contractExecuted: true, opsStable: false, financeRecovery: false },
    creditRisk: { friskScore: 5, insolvencyProbability: 0.055, creditRating: "BB+", paymentBehavior: "Moderate", bankruptcyRisk12m: "Moderate", lastUpdated: "6 days ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 61, grade: "C", environmental: 58, social: 63, governance: 62, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Compliant", scope3Status: "In Progress", conflictMineralsStatus: "Compliant", laborRisk: "Low", environmentalRisk: "Medium", carbonFootprint: "8.9kt CO₂e", lastAudit: "Jul 2025" },
    resiliency: { overall: 6.2, transparency: 6.4, network: 5.8, continuity: 6.2, performance: 6.4, maturity: 6.2, lastUpdated: "Q3 2025" },
    alerts: [{ id: "al-hay-1", type: "risk", text: "Net margin compressed to 6.1% — nickel and cobalt input cost headwinds", date: "2025-09-30" }],
    timeline: [
      { date: "Sep 15, 2025", text: "Q3 earnings — guidance lowered, alloy input cost headwinds cited by management" },
      { date: "Sep 22, 2025", text: "Procurement initiated 90-day observation window" },
      { date: "Oct 03, 2025", text: "Supply agreement amended — 45-day safety stock buffer established for alloy rod" },
    ],
  },
  // ── Emerson Electric — STABLE · LOW RISK ───────────────────────────────────
  {
    id: "eme", name: "Emerson Electric", ticker: "EMR",
    website: "https://www.emerson.com",
    countryCode: "US", region: "NA", tier: 1,
    category: "Electronic Controls", categoryConfidence: "High",
    spend: 18.5, exposure: 5.2, risk: 24,
    onTime: 97, qualityPPM: 65, riskState: "STABLE",
    riskHistory: [26, 25, 24, 24, 23, 24, 25, 24, 23, 24, 24, 24],
    data: { updatedLabel: "Updated: 1 day ago", confidence: "HIGH" },
    ratios: { debtToEquity: 0.54, netProfitMargin: 0.124, currentRatio: 1.78 },
    financialHealth: {
      score: 86,
      dioTrend: [32, 31, 31, 30],
      dsoTrend: [38, 37, 37, 36],
      dpoCurrent: 44,
      cccTrend: [26, 24, 24, 22],
      inventoryGrowthYoY: 0.03,
      revenueGrowthYoY: 0.08,
      netDebtEbitda: [0.7, 0.6, 0.6, 0.6, 0.5, 0.5, 0.5, 0.4],
      interestCoverage: 16.8,
      capexToDepreciation: [1.44, 1.48, 1.52, 1.55],
      flags: [],
    },
    duns: "04-228-3312",
    creditRisk: { friskScore: 9, insolvencyProbability: 0.003, creditRating: "A", paymentBehavior: "Good", bankruptcyRisk12m: "Low", lastUpdated: "1 day ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 84, grade: "A", environmental: 86, social: 83, governance: 82, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Compliant", scope3Status: "Reported", conflictMineralsStatus: "Compliant", laborRisk: "Low", environmentalRisk: "Low", carbonFootprint: "18.2kt CO₂e", lastAudit: "Aug 2025" },
    resiliency: { overall: 8.8, transparency: 9.0, network: 8.6, continuity: 8.9, performance: 8.8, maturity: 8.7, lastUpdated: "Q3 2025" },
    alerts: [],
  },
  // ── Parker Hannifin — STABLE ────────────────────────────────────────────────
  {
    id: "phn", name: "Parker Hannifin", ticker: "PH",
    website: "https://www.parker.com",
    countryCode: "US", region: "NA", tier: 1,
    category: "Fluid Systems", categoryConfidence: "High",
    spend: 12.2, exposure: 3.8, risk: 29,
    onTime: 96, qualityPPM: 92, riskState: "STABLE",
    riskHistory: [28, 28, 29, 28, 29, 30, 29, 28, 29, 29, 29, 29],
    data: { updatedLabel: "Updated: 3 days ago", confidence: "HIGH" },
    ratios: { debtToEquity: 0.88, netProfitMargin: 0.098, currentRatio: 1.62 },
    duns: "05-339-7821",
    creditRisk: { friskScore: 8, insolvencyProbability: 0.008, creditRating: "A-", paymentBehavior: "Good", bankruptcyRisk12m: "Low", lastUpdated: "3 days ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 78, grade: "B", environmental: 80, social: 77, governance: 76, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Compliant", scope3Status: "Reported", conflictMineralsStatus: "Compliant", laborRisk: "Low", environmentalRisk: "Low", carbonFootprint: "14.6kt CO₂e", lastAudit: "Sep 2025" },
    resiliency: { overall: 8.4, transparency: 8.6, network: 8.2, continuity: 8.5, performance: 8.4, maturity: 8.3, lastUpdated: "Q3 2025" },
    alerts: [],
  },
  // ── Honeywell Sensing — MEDIUM RISK · UNDER OBSERVATION ────────────────────
  {
    id: "hon", name: "Honeywell Sensing", ticker: "HON",
    website: "https://sensing.honeywell.com",
    countryCode: "US", region: "NA", tier: 1,
    category: "Sensors & Controls", categoryConfidence: "High",
    spend: 9.8, exposure: 3.1, risk: 46,
    onTime: 93, qualityPPM: 145, riskState: "UNDER OBSERVATION",
    riskHistory: [35, 36, 38, 39, 40, 42, 43, 44, 44, 45, 45, 46],
    data: { updatedLabel: "Updated: 4 days ago", confidence: "MEDIUM" },
    ratios: { debtToEquity: 1.12, netProfitMargin: 0.072, currentRatio: 1.38 },
    duns: "06-441-9832",
    creditRisk: { friskScore: 7, insolvencyProbability: 0.024, creditRating: "BBB+", paymentBehavior: "Good", bankruptcyRisk12m: "Low", lastUpdated: "4 days ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 76, grade: "B", environmental: 78, social: 75, governance: 74, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Compliant", scope3Status: "In Progress", conflictMineralsStatus: "Compliant", laborRisk: "Low", environmentalRisk: "Low", carbonFootprint: "11.2kt CO₂e", lastAudit: "Jun 2025" },
    resiliency: { overall: 7.2, transparency: 7.4, network: 6.9, continuity: 7.2, performance: 7.3, maturity: 7.2, lastUpdated: "Q3 2025" },
    alerts: [{ id: "al-hon-1", type: "logistics", text: "Sensor delivery extended to 10 weeks — semiconductor allocation constraints", date: "2025-09-22" }],
  },
  // ── XPO Inc. — STABLE ──────────────────────────────────────────────────────
  {
    id: "xpo", name: "XPO Inc.", ticker: "XPO",
    website: "https://www.xpo.com",
    countryCode: "US", region: "NA", tier: 1,
    category: "Logistics", categoryConfidence: "High",
    spend: 8.4, exposure: 2.6, risk: 35,
    onTime: 97, qualityPPM: 48, riskState: "STABLE",
    riskHistory: [32, 33, 34, 33, 34, 35, 35, 34, 35, 35, 35, 35],
    data: { updatedLabel: "Updated: 2 days ago", confidence: "HIGH" },
    ratios: { debtToEquity: 1.44, netProfitMargin: 0.048, currentRatio: 1.02 },
    duns: "09-882-1144",
    creditRisk: { friskScore: 6, insolvencyProbability: 0.038, creditRating: "BB+", paymentBehavior: "Good", bankruptcyRisk12m: "Low", lastUpdated: "2 days ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 64, grade: "C", environmental: 61, social: 66, governance: 64, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Compliant", scope3Status: "In Progress", conflictMineralsStatus: "N/A", laborRisk: "Low", environmentalRisk: "Medium", carbonFootprint: "31.8kt CO₂e", lastAudit: "May 2025" },
    resiliency: { overall: 7.8, transparency: 7.6, network: 7.9, continuity: 7.8, performance: 8.0, maturity: 7.7, lastUpdated: "Q3 2025" },
    alerts: [],
  },
  // ── Moog Inc. — STABLE ─────────────────────────────────────────────────────
  {
    id: "mog", name: "Moog Inc.", ticker: "MOG.A",
    website: "https://www.moog.com",
    countryCode: "US", region: "NA", tier: 2,
    category: "Components", categoryConfidence: "High",
    spend: 6.1, exposure: 2.8, risk: 36,
    onTime: 95, qualityPPM: 112, riskState: "STABLE",
    riskHistory: [34, 35, 36, 35, 36, 36, 37, 36, 36, 36, 36, 36],
    data: { updatedLabel: "Updated: 1 week ago", confidence: "HIGH" },
    ratios: { debtToEquity: 1.22, netProfitMargin: 0.084, currentRatio: 1.45 },
    duns: "03-774-9921",
    creditRisk: { friskScore: 7, insolvencyProbability: 0.018, creditRating: "BBB", paymentBehavior: "Good", bankruptcyRisk12m: "Low", lastUpdated: "1 week ago", source: "CreditRiskMonitor FRISK" },
    esg: { score: 72, grade: "B", environmental: 74, social: 71, governance: 70, eudrCompliant: "Not Started", csdddStatus: "N/A", lksgStatus: "N/A", csrdStatus: "N/A", uflpaStatus: "Compliant", scope3Status: "In Progress", conflictMineralsStatus: "Compliant", laborRisk: "Low", environmentalRisk: "Low", carbonFootprint: "7.4kt CO₂e", lastAudit: "Aug 2025" },
    resiliency: { overall: 7.9, transparency: 8.1, network: 7.7, continuity: 8.0, performance: 7.9, maturity: 7.8, lastUpdated: "Q3 2025" },
    alerts: [],
  },
];

export const suppliersAllUS: Supplier[] = suppliersGovernedUS
  .map((s) => ({ ...s, risk: computeRisk(s) }));

// ── US Live Events ────────────────────────────────────────────────────────────
export const LIVE_EVENTS_US: LiveEvent[] = [
  {
    id: "us-ev-001", category: "regulatory", severity: "critical",
    title: "UFLPA Enforcement — Zhonghe Precision Electronics Detained",
    detail: "CBP has detained a shipment from Zhonghe Precision at Port of Long Beach under the Uyghur Forced Labor Prevention Act. Documentation indicates Tier 3 raw material sourcing from Xinjiang region. Presumption of forced labor applies — supplier must rebut with clear and convincing evidence.",
    region: "NA", country: "United States", affectedSupplierIds: ["zhp"],
    estimatedImpact: "$1.8M shipment value at risk",
    leadTimeExtension: "6–10 weeks",
    date: "1d ago", source: "CBP / UFLPA Entity List", status: "Active",
  },
  {
    id: "us-ev-002", category: "financial", severity: "high",
    title: "Flex Ltd. — Q2 Earnings Miss & Margin Compression",
    detail: "Flex Ltd. reported Q2 revenue 12% below guidance. EBITDA margin fell to 3.2% on customer program delays and component cost inflation. FRISK score declined from 6 to 4. Delivery lead times for PCB assemblies extended to 16 weeks.",
    region: "APAC", country: "United States", affectedSupplierIds: ["flx"],
    estimatedImpact: "$4.2M exposure at risk",
    date: "2d ago", source: "Flex Ltd. Investor Relations / CreditRiskMonitor", status: "Active",
  },
  {
    id: "us-ev-003", category: "logistics", severity: "high",
    title: "ILA East Coast Port Slowdown — Container Backlog Building",
    detail: "International Longshoremen's Association work-to-rule action at East Coast ports causing 3–5 day clearance delays. Baltimore and Savannah most affected. Inbound components from European and Asian suppliers experiencing increased dwell times.",
    region: "NA", country: "United States", affectedSupplierIds: ["flx", "zhp"],
    estimatedImpact: "$0.6M delay costs",
    leadTimeExtension: "3–5 days",
    date: "3d ago", source: "ILA / American Association of Port Authorities", status: "Monitoring",
  },
  {
    id: "us-ev-004", category: "geopolitical", severity: "high",
    title: "US–China Tariff Escalation — Electronic Components",
    detail: "USTR imposed additional 15% tariff on precision electronic components and sensor assemblies imported from China. Effective 60 days from publication. Zhonghe Precision and other CN-sourced components face increased landed cost.",
    region: "NA", country: "United States", affectedSupplierIds: ["zhp"],
    estimatedImpact: "$0.7M annual cost increase",
    date: "4d ago", source: "USTR / Federal Register", status: "Active",
  },
  {
    id: "us-ev-005", category: "financial", severity: "medium",
    title: "Haynes International — Alloy Input Cost Headwinds",
    detail: "Nickel and cobalt spot prices elevated 18% YTD. Haynes International Q3 guidance lowered — net margin compressed to 6.1%. Observation window initiated. Safety stock build recommended for specialty alloy rod.",
    region: "NA", country: "United States", affectedSupplierIds: ["hay"],
    estimatedImpact: "$1.2M exposure",
    date: "5d ago", source: "Haynes International / CreditRiskMonitor FRISK", status: "Monitoring",
  },
];

// ── US Shipments ──────────────────────────────────────────────────────────────
export const SHIPMENTS_US: Shipment[] = [
  { id: "SHP-US-4401", supplierId: "eme", origin: "St. Louis, MO", destination: "Chicago, IL", carrier: "XPO Inc.", eta: "Oct 18, 2025", delayRisk: "Low", status: "On Track", value: "$2.4M" },
  { id: "SHP-US-4412", supplierId: "flx", origin: "Austin, TX", destination: "Chicago, IL", carrier: "FedEx Freight", eta: "Oct 24, 2025", delayDays: 8, delayRisk: "High", status: "Delayed", value: "$1.6M" },
  { id: "SHP-US-4419", supplierId: "zhp", origin: "Shenzhen, CN", destination: "Long Beach, CA", carrier: "Maersk", eta: "Oct 21, 2025", delayDays: 14, delayRisk: "High", status: "Customs Hold", value: "$1.8M" },
  { id: "SHP-US-4428", supplierId: "phn", origin: "Cleveland, OH", destination: "Chicago, IL", carrier: "XPO Inc.", eta: "Oct 15, 2025", delayRisk: "Low", status: "On Track", value: "$1.1M" },
  { id: "SHP-US-4437", supplierId: "hay", origin: "Kokomo, IN", destination: "Chicago, IL", carrier: "Old Dominion", eta: "Oct 19, 2025", delayDays: 3, delayRisk: "Medium", status: "At Risk", value: "$0.8M" },
  { id: "SHP-US-4449", supplierId: "hon", origin: "Morris Plains, NJ", destination: "Chicago, IL", carrier: "UPS Freight", eta: "Oct 22, 2025", delayRisk: "Low", status: "On Track", value: "$0.9M" },
  { id: "SHP-US-4461", supplierId: "mog", origin: "East Aurora, NY", destination: "Chicago, IL", carrier: "FedEx Freight", eta: "Oct 17, 2025", delayRisk: "Low", status: "On Track", value: "$0.7M" },
];

// ── US Contracts ──────────────────────────────────────────────────────────────
export const CONTRACTS_US: Contract[] = [
  { id: "us-co-01", supplierId: "flx", supplierName: "Flex Ltd.", title: "EMS-FRAME-2023", type: "Master Services", expires: "2025-12-31", value: "$14.2M", status: "Under Renegotiation", autoRenew: false },
  { id: "us-co-02", supplierId: "eme", supplierName: "Emerson Electric", title: "CTRL-SLA-2024", type: "Supply & Service", expires: "2026-06-30", value: "$18.5M", status: "Active", autoRenew: true },
  { id: "us-co-03", supplierId: "phn", supplierName: "Parker Hannifin", title: "FLUID-QPA-2024", type: "Quality & Price", expires: "2026-03-31", value: "$12.2M", status: "Active", autoRenew: true },
  { id: "us-co-04", supplierId: "hay", supplierName: "Haynes International", title: "ALLOY-LTA-2022", type: "Long-term Agreement", expires: "2025-11-15", value: "$5.6M", status: "Pending Renewal", autoRenew: false },
  { id: "us-co-05", supplierId: "xpo", supplierName: "XPO Inc.", title: "LOG-NA-FRAME-24", type: "Framework", expires: "2026-09-30", value: "$8.4M", status: "Active", autoRenew: true },
  { id: "us-co-06", supplierId: "zhp", supplierName: "Zhonghe Precision", title: "PREC-MSA-2023", type: "Master Services", expires: "2025-10-31", value: "$4.8M", status: "Under Renegotiation", autoRenew: false },
  { id: "us-co-07", supplierId: "hon", supplierName: "Honeywell Sensing", title: "SENSOR-QPA-2024", type: "Quality & Price", expires: "2026-02-28", value: "$9.8M", status: "Active", autoRenew: false },
];

// ── US Crisis Rooms ───────────────────────────────────────────────────────────
export const CRISIS_ROOMS_US: CrisisRoom[] = [
  {
    id: "us-cr-001",
    title: "Zhonghe Precision — UFLPA Compliance Escalation",
    triggeredBy: "us-ev-001",
    severity: "critical",
    openedDate: "Oct 01, 2025",
    owner: "Sarah Renwick",
    affectedSupplierIds: ["zhp"],
    affectedParts: ["PCB Sub-Assembly ZHP-44", "Precision Connector PC-220", "Sensor Housing SH-08"],
    estimatedExposure: "$4.8M",
    status: "Open",
    actions: [
      { id: "ua1", text: "Engage trade compliance counsel for UFLPA rebuttal documentation", owner: "Legal — T. Morrison", due: "Oct 08", done: false },
      { id: "ua2", text: "Identify alternative CN and non-CN suppliers for PCB sub-assemblies", owner: "M. Chen — Procurement", due: "Oct 12", done: false },
      { id: "ua3", text: "Increase safety stock on ZHP-44 sub-assembly to 60-day buffer", owner: "J. Park — Ops", due: "Oct 07", done: true },
      { id: "ua4", text: "Notify production planning — potential PCB shortage from Week 44", owner: "R. Torres — Planning", due: "Oct 06", done: true },
    ],
  },
  {
    id: "us-cr-002",
    title: "Flex Ltd. — Financial Deterioration & Delivery Risk",
    triggeredBy: "us-ev-002",
    severity: "high",
    openedDate: "Oct 02, 2025",
    owner: "M. Chen",
    affectedSupplierIds: ["flx"],
    affectedParts: ["Control Board CB-3100", "Power Module PM-14", "Interface Assembly IA-7"],
    estimatedExposure: "$6.8M",
    status: "Open",
    actions: [
      { id: "ub1", text: "Weekly FRISK score monitoring — escalate if score drops to 3", owner: "A. Patel — Risk", due: "Ongoing", done: false },
      { id: "ub2", text: "Qualify Jabil Circuit as secondary EMS source for CB-3100", owner: "M. Chen — Procurement", due: "Oct 20", done: false },
      { id: "ub3", text: "Negotiate net-60 payment terms to improve Flex cash position", owner: "Finance", due: "Oct 10", done: true },
      { id: "ub4", text: "30-day safety stock build for CB-3100 and PM-14 critical assemblies", owner: "J. Park — Ops", due: "Oct 08", done: true },
    ],
  },
  {
    id: "us-cr-003",
    title: "ILA Port Slowdown — East Coast Inbound Delays",
    triggeredBy: "us-ev-003",
    severity: "high",
    openedDate: "Oct 07, 2025",
    owner: "R. Torres",
    affectedSupplierIds: ["flx", "zhp"],
    affectedParts: ["PCB Sub-Assembly ZHP-44", "Control Board CB-3100"],
    estimatedExposure: "$2.4M",
    status: "Contained",
    actions: [
      { id: "uc1", text: "Reroute Flex shipment SHP-US-4412 via air freight — cost delta approved", owner: "M. Chen — Procurement", due: "Oct 09", done: true },
      { id: "uc2", text: "Confirm updated ETA from Maersk on detained Zhonghe shipment", owner: "R. Torres — Logistics", due: "Oct 08", done: true },
      { id: "uc3", text: "Evaluate Gulf Coast port alternatives for future Shenzhen shipments", owner: "M. Chen — Procurement", due: "Oct 15", done: false },
    ],
  },
];

// ── US Global Alerts ──────────────────────────────────────────────────────────
export const GLOBAL_ALERTS_US: GlobalAlert[] = [
  { id: "us-ga-01", supplierId: "zhp", text: "Zhonghe Precision UFLPA violation — CBP detention at Long Beach, trade compliance escalated", type: "risk", date: "1d ago" },
  { id: "us-ga-02", supplierId: "flx", text: "Flex Ltd. observation window — FRISK 4, Q2 earnings miss, delivery risk elevated", type: "observation", date: "2d ago" },
  { id: "us-ga-03", supplierId: "hay", text: "Haynes International ALLOY-LTA-2022 contract renewal window open (32 days remaining)", type: "contract", date: "3d ago" },
  { id: "us-ga-04", supplierId: "hon", text: "Honeywell Sensing lead times extended to 10 weeks — semiconductor allocation issue", type: "logistics", date: "5d ago" },
];

// ── US Recovery Profiles ──────────────────────────────────────────────────────
export const RECOVERY_PROFILES_US: Record<string, RecoveryProfile> = {
  flx: { inventoryBufferDays: 22, timeToSurvive: 22, timeToRecover: 120, criticalComponents: ["Control Board CB-3100", "Power Module PM-14", "PCB Sub-Assembly FLX-PCB-44"], affectedProductLines: ["ProControl 2000", "SensorSuite Platform"], alternativeQualified: false, safetyStockRecommendation: 45, lastReviewed: "Oct 2025" },
  zhp: { inventoryBufferDays: 14, timeToSurvive: 14, timeToRecover: 90, criticalComponents: ["Precision Connector ZHP-CONN-08", "Precision Housing ZHP-PREC-04", "PCB Connector PC-220"], affectedProductLines: ["ProControl 2000", "SensorSuite Platform"], alternativeQualified: false, safetyStockRecommendation: 60, lastReviewed: "Oct 2025" },
  hay: { inventoryBufferDays: 35, timeToSurvive: 35, timeToRecover: 60, criticalComponents: ["Nickel Alloy Rod HAY-230", "Cobalt Alloy Sheet HAY-188", "High-Temp Alloy Bar HAY-C276"], affectedProductLines: ["FlexDrive Series", "ProControl 2000"], alternativeQualified: true, safetyStockRecommendation: 45, lastReviewed: "Sep 2025" },
  eme: { inventoryBufferDays: 60, timeToSurvive: 60, timeToRecover: 45, criticalComponents: ["Control Board EMR-CB-3100", "Interface Controller EMR-INT-44"], affectedProductLines: ["ProControl 2000", "SensorSuite Platform"], alternativeQualified: true, safetyStockRecommendation: 30, lastReviewed: "Aug 2025" },
  phn: { inventoryBufferDays: 45, timeToSurvive: 45, timeToRecover: 60, criticalComponents: ["Hydraulic Module PH-HYD-220", "Seal Assembly PH-SA-14"], affectedProductLines: ["FlexDrive Series"], alternativeQualified: true, safetyStockRecommendation: 30, lastReviewed: "Sep 2025" },
  hon: { inventoryBufferDays: 28, timeToSurvive: 28, timeToRecover: 55, criticalComponents: ["Multi-Axis Sensor HON-MULTI-88", "Industrial Sensor HON-SENS-12"], affectedProductLines: ["ProControl 2000", "FlexDrive Series", "SensorSuite Platform"], alternativeQualified: false, safetyStockRecommendation: 40, lastReviewed: "Sep 2025" },
  xpo: { inventoryBufferDays: 7, timeToSurvive: 7, timeToRecover: 14, criticalComponents: ["Midwest Freight Lanes", "Last-mile Delivery Network", "Cross-dock Operations"], affectedProductLines: ["All product lines"], alternativeQualified: true, safetyStockRecommendation: 14, lastReviewed: "Oct 2025" },
  mog: { inventoryBufferDays: 30, timeToSurvive: 30, timeToRecover: 75, criticalComponents: ["Precision Drive Assembly MOG-DRV-14", "Servo Actuator MOG-SA-08"], affectedProductLines: ["FlexDrive Series"], alternativeQualified: false, safetyStockRecommendation: 35, lastReviewed: "Oct 2025" },
};

// ── US Certifications ─────────────────────────────────────────────────────────
export const CERTIFICATIONS_US: Record<string, Certification[]> = {
  eme: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "Bureau Veritas", issued: "2023-01-15", expires: "2026-01-14", status: "Valid", scope: "Industrial automation controls design & manufacture" },
    { name: "AS9100D:2016", standard: "AS9100D", issuer: "NSF International", issued: "2022-06-01", expires: "2025-05-31", status: "Expiring Soon", scope: "Aerospace quality management — control systems" },
    { name: "UL Listed", standard: "UL", issuer: "Underwriters Laboratories", issued: "2024-01-01", expires: "2026-12-31", status: "Valid", scope: "Electronic control assemblies for industrial use" },
  ],
  phn: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "DNV GL", issued: "2023-04-01", expires: "2026-03-31", status: "Valid" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "DNV GL", issued: "2023-04-01", expires: "2026-03-31", status: "Valid" },
    { name: "ITAR Registered", standard: "ITAR", issuer: "US Dept of State DDTC", issued: "2022-08-01", expires: "2025-08-31", status: "Expiring Soon", scope: "Hydraulic and pneumatic systems for defense" },
  ],
  hon: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "TÜV SÜD", issued: "2023-09-01", expires: "2026-08-31", status: "Valid" },
    { name: "IATF 16949:2016", standard: "IATF 16949", issuer: "TÜV SÜD", issued: "2023-09-01", expires: "2026-08-31", status: "Valid", scope: "Automotive-grade sensor manufacturing" },
    { name: "C-TPAT Certified", standard: "C-TPAT", issuer: "US Customs & Border Protection", issued: "2021-03-15", expires: "2026-03-15", status: "Valid", scope: "Customs-Trade Partnership Against Terrorism" },
  ],
  xpo: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "Bureau Veritas", issued: "2024-01-01", expires: "2027-01-01", status: "Valid", scope: "Freight transportation and logistics operations" },
    { name: "C-TPAT Certified", standard: "C-TPAT", issuer: "US Customs & Border Protection", issued: "2020-06-01", expires: "2026-06-01", status: "Valid", scope: "Supply chain security management" },
    { name: "ISO 28000:2022", standard: "ISO 28000", issuer: "Lloyd's Register", issued: "2024-03-01", expires: "2027-03-01", status: "Valid", scope: "Supply chain security management system" },
  ],
  hay: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "SGS", issued: "2022-11-01", expires: "2025-10-31", status: "Expiring Soon" },
    { name: "AS9100D:2016", standard: "AS9100D", issuer: "NSF International", issued: "2023-03-01", expires: "2026-02-28", status: "Valid", scope: "Specialty alloy production for aerospace applications" },
    { name: "NADCAP", standard: "NADCAP", issuer: "Performance Review Institute", issued: "2023-07-01", expires: "2025-06-30", status: "Expiring Soon", scope: "Heat treating of nickel and cobalt alloys" },
  ],
  mog: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "Bureau Veritas", issued: "2023-08-01", expires: "2026-07-31", status: "Valid" },
    { name: "AS9100D:2016", standard: "AS9100D", issuer: "Bureau Veritas", issued: "2023-08-01", expires: "2026-07-31", status: "Valid", scope: "Precision motion control for aerospace & industrial" },
    { name: "ITAR Registered", standard: "ITAR", issuer: "US Dept of State DDTC", issued: "2023-01-15", expires: "2026-01-14", status: "Valid", scope: "Defense-related precision actuation systems" },
    { name: "NADCAP", standard: "NADCAP", issuer: "Performance Review Institute", issued: "2024-01-01", expires: "2026-12-31", status: "Valid", scope: "Special processes — NDT and chemical processing" },
  ],
  flx: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "TÜV SÜD", issued: "2022-05-01", expires: "2025-04-30", status: "Expiring Soon" },
    { name: "ISO 14001:2015", standard: "ISO 14001", issuer: "TÜV SÜD", issued: "2022-05-01", expires: "2025-04-30", status: "Expiring Soon" },
    { name: "IATF 16949:2016", standard: "IATF 16949", issuer: "TÜV SÜD", issued: "2023-02-01", expires: "2026-01-31", status: "Valid", scope: "Automotive electronics manufacturing services" },
  ],
  zhp: [
    { name: "ISO 9001:2015", standard: "ISO 9001", issuer: "CQC", issued: "2020-09-01", expires: "2023-08-31", status: "Expired", scope: "Precision mechanical components" },
    { name: "RoHS Compliance", standard: "RoHS", issuer: "Self-declaration", issued: "2023-01-01", expires: "2025-12-31", status: "Expiring Soon", scope: "Restriction of hazardous substances in electronics" },
  ],
};

// ── US Product Lines (Meridian Industrial Group) ──────────────────────────────
export const PRODUCT_LINES_US: ProductLine[] = [
  {
    id: "mpc", name: "ProControl 2000", model: "MPC2000-24/48/96", annualVolume: 28000,
    bomItems: [
      { partNumber: "EMR-CB-3100", partName: "Control Board Assembly", supplierId: "eme", quantity: 1, unitCost: 185, leadTimeDays: 14, soloSourced: false, riskScore: 24 },
      { partNumber: "FLX-PCB-44",  partName: "PCB Sub-Assembly",       supplierId: "flx", quantity: 2, unitCost: 92,  leadTimeDays: 16, soloSourced: true,  riskScore: 68 },
      { partNumber: "HON-SENS-12", partName: "Industrial Sensor",       supplierId: "hon", quantity: 3, unitCost: 45,  leadTimeDays: 10, soloSourced: false, riskScore: 46 },
      { partNumber: "ZHP-CONN-08", partName: "Precision Connector",     supplierId: "zhp", quantity: 8, unitCost: 12,  leadTimeDays: 21, soloSourced: true,  riskScore: 78 },
    ],
  },
  {
    id: "mfd", name: "FlexDrive Series", model: "MFD-5/10/25/50HP", annualVolume: 14500,
    bomItems: [
      { partNumber: "PH-HYD-220",  partName: "Hydraulic Module",          supplierId: "phn", quantity: 1, unitCost: 340, leadTimeDays: 14, soloSourced: false, riskScore: 29 },
      { partNumber: "MOG-DRV-14",  partName: "Precision Drive Assembly",   supplierId: "mog", quantity: 1, unitCost: 480, leadTimeDays: 21, soloSourced: true,  riskScore: 36 },
      { partNumber: "HON-SENS-12", partName: "Motion Sensor",              supplierId: "hon", quantity: 2, unitCost: 38,  leadTimeDays: 10, soloSourced: false, riskScore: 46 },
      { partNumber: "FLX-PWR-22",  partName: "Power Module Assembly",      supplierId: "flx", quantity: 1, unitCost: 125, leadTimeDays: 16, soloSourced: false, riskScore: 68 },
    ],
  },
  {
    id: "mss", name: "SensorSuite Platform", model: "MSS-8/16/32 Channel", annualVolume: 42000,
    bomItems: [
      { partNumber: "HON-MULTI-88", partName: "Multi-Axis Sensor",      supplierId: "hon", quantity: 4, unitCost: 62,  leadTimeDays: 10, soloSourced: false, riskScore: 46 },
      { partNumber: "EMR-INT-44",   partName: "Interface Controller",   supplierId: "eme", quantity: 1, unitCost: 95,  leadTimeDays: 14, soloSourced: false, riskScore: 24 },
      { partNumber: "ZHP-PREC-04",  partName: "Precision Housing",      supplierId: "zhp", quantity: 4, unitCost: 18,  leadTimeDays: 21, soloSourced: false, riskScore: 78 },
      { partNumber: "FLX-PROC-08",  partName: "Processing Board",       supplierId: "flx", quantity: 1, unitCost: 145, leadTimeDays: 16, soloSourced: true,  riskScore: 68 },
    ],
  },
];

// ── US Commodity Prices ───────────────────────────────────────────────────────
export const COMMODITIES_US: CommodityPrice[] = [
  { id: "nickel", name: "Nickel (LME)", unit: "tonne", currentPrice: 16420, currency: "USD", priceHistory: [14200, 15100, 15800, 17200, 18400, 17800, 17100, 16600, 16420], changePercent: 8.4, trend: "Rising", volatility: "High", affectedCategories: ["Raw Materials"], affectedSupplierIds: ["hay"], alert: "Nickel +8.4% YTD — Haynes International alloy input cost headwinds elevated" },
  { id: "cobalt", name: "Cobalt (LME)", unit: "tonne", currentPrice: 32800, currency: "USD", priceHistory: [28000, 29400, 31200, 34500, 36800, 35200, 34100, 33200, 32800], changePercent: 17.1, trend: "Rising", volatility: "High", affectedCategories: ["Raw Materials"], affectedSupplierIds: ["hay"], alert: "Cobalt +17% YTD — Haynes specialty alloy margin compression anticipated at next pricing review" },
  { id: "copper-us", name: "Copper (COMEX)", unit: "lb", currentPrice: 4.12, currency: "USD", priceHistory: [3.65, 3.82, 3.95, 4.20, 4.35, 4.28, 4.18, 4.08, 4.12], changePercent: 4.3, trend: "Rising", volatility: "Medium", affectedCategories: ["Electronics", "Components"], affectedSupplierIds: ["flx", "hon"], alert: "Copper +4.3% QoQ — PCB and sensor cost pressure expected at contract review" },
  { id: "rare-earth-us", name: "Rare Earth Index", unit: "index", currentPrice: 168, currency: "USD", priceHistory: [138, 144, 150, 158, 172, 185, 178, 165, 168], changePercent: -4.2, trend: "Falling", volatility: "High", affectedCategories: ["Electronics"], affectedSupplierIds: ["flx", "zhp"], alert: "⚠ Rare earth export restrictions from China — UFLPA enforcement compounds supply risk for Zhonghe" },
  { id: "semiconductors", name: "Semiconductor IC Index", unit: "index", currentPrice: 224, currency: "USD", priceHistory: [180, 188, 195, 210, 228, 240, 235, 228, 224], changePercent: 24.4, trend: "Rising", volatility: "High", affectedCategories: ["Electronics", "Sensors & Controls"], affectedSupplierIds: ["flx", "hon", "eme"], alert: "Semiconductor allocation tightening — Flex and Honeywell lead times extended 10–16 weeks" },
  { id: "henry-hub", name: "Natural Gas (Henry Hub)", unit: "MMBtu", currentPrice: 2.84, currency: "USD", priceHistory: [2.20, 2.35, 2.55, 3.10, 3.45, 3.20, 2.95, 2.88, 2.84], changePercent: 29.1, trend: "Rising", volatility: "High", affectedCategories: ["Raw Materials", "Logistics"], affectedSupplierIds: ["hay", "xpo"], alert: undefined },
];

// ── US Assessments ────────────────────────────────────────────────────────────
export const ASSESSMENTS_US: Assessment[] = [
  { supplierId: "zhp", supplierName: "Zhonghe Precision",   templateId: "uflpa-review", templateName: "UFLPA Compliance Review",          sentDate: "Sep 28, 2025", dueDate: "Oct 10, 2025", status: "Overdue",    completionPct: 15,  riskFlags: 6 },
  { supplierId: "flx", supplierName: "Flex Ltd.",            templateId: "fin-health",   templateName: "Financial Health Check",           sentDate: "Sep 22, 2025", dueDate: "Oct 05, 2025", completedDate: "Oct 08, 2025", status: "Completed",  completionPct: 100, riskFlags: 3 },
  { supplierId: "hay", supplierName: "Haynes International", templateId: "fin-health",   templateName: "Financial Health Check",           sentDate: "Oct 01, 2025", dueDate: "Oct 20, 2025", status: "In Progress", completionPct: 55,  riskFlags: 2 },
  { supplierId: "hon", supplierName: "Honeywell Sensing",    templateId: "single-src",   templateName: "Single Source Dependency Review",  sentDate: "Oct 08, 2025", dueDate: "Oct 25, 2025", status: "Sent",        completionPct: 0,   riskFlags: 0 },
  { supplierId: "eme", supplierName: "Emerson Electric",     templateId: "sub-tier",     templateName: "Sub-tier Disclosure Questionnaire", status: "Not Sent", completionPct: 0, riskFlags: 0 },
  { supplierId: "phn", supplierName: "Parker Hannifin",      templateId: "dis-rec",      templateName: "Disaster Recovery Assessment",      status: "Not Sent", completionPct: 0, riskFlags: 0 },
  { supplierId: "mog", supplierName: "Moog Inc.",             templateId: "sub-tier",     templateName: "Sub-tier Disclosure Questionnaire", status: "Not Sent", completionPct: 0, riskFlags: 0 },
  { supplierId: "xpo", supplierName: "XPO Inc.",              templateId: "dis-rec",      templateName: "Disaster Recovery Assessment",      status: "Not Sent", completionPct: 0, riskFlags: 0 },
];

// ── US Industry Benchmarks ────────────────────────────────────────────────────
export const BENCHMARKS_US: IndustryBenchmark[] = [
  { sector: "Industrial Automation (Your Portfolio)", avgRiskScore: 44, avgDPS: 41, avgOnTime: 93, avgESGScore: 66, sampleSize: 8 },
  { sector: "Industrial Automation Industry Avg",     avgRiskScore: 49, avgDPS: 46, avgOnTime: 92, avgESGScore: 64, sampleSize: 312 },
  { sector: "Electronic Manufacturing Services (EMS)", avgRiskScore: 58, avgDPS: 54, avgOnTime: 88, avgESGScore: 58, sampleSize: 840 },
  { sector: "Specialty Alloys & Materials",            avgRiskScore: 52, avgDPS: 48, avgOnTime: 90, avgESGScore: 61, sampleSize: 180 },
  { sector: "Industrial Logistics (North America)",    avgRiskScore: 34, avgDPS: 30, avgOnTime: 96, avgESGScore: 62, sampleSize: 520 },
];
